/* tslint:disable */
/* eslint-disable */
/**
 * sudosos-back-end
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AcceptTosRequest
 */
export interface AcceptTosRequest {
    /**
     * Whether data about this
     * user can be used (non-anonymously) for more data science!
     * @type {boolean}
     * @memberof AcceptTosRequest
     */
    extensiveDataProcessing: boolean;
}

/**
 * Check if a given object implements the AcceptTosRequest interface.
 */
export function instanceOfAcceptTosRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "extensiveDataProcessing" in value;

    return isInstance;
}

export function AcceptTosRequestFromJSON(json: any): AcceptTosRequest {
    return AcceptTosRequestFromJSONTyped(json, false);
}

export function AcceptTosRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AcceptTosRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'extensiveDataProcessing': json['extensiveDataProcessing'],
    };
}

export function AcceptTosRequestToJSON(value?: AcceptTosRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'extensiveDataProcessing': value.extensiveDataProcessing,
    };
}

