/* tslint:disable */
/* eslint-disable */
/**
 * sudosos-back-end
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { RelationResponse } from './RelationResponse';
import {
    RelationResponseFromJSON,
    RelationResponseFromJSONTyped,
    RelationResponseToJSON,
} from './RelationResponse';

/**
 * 
 * @export
 * @interface ActionResponse
 */
export interface ActionResponse {
    /**
     * The name of the action performed on the entity.
     * @type {string}
     * @memberof ActionResponse
     */
    action?: string;
    /**
     * 
     * @type {Array<RelationResponse>}
     * @memberof ActionResponse
     */
    relations?: Array<RelationResponse>;
}

/**
 * Check if a given object implements the ActionResponse interface.
 */
export function instanceOfActionResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ActionResponseFromJSON(json: any): ActionResponse {
    return ActionResponseFromJSONTyped(json, false);
}

export function ActionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ActionResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'action': !exists(json, 'action') ? undefined : json['action'],
        'relations': !exists(json, 'relations') ? undefined : ((json['relations'] as Array<any>).map(RelationResponseFromJSON)),
    };
}

export function ActionResponseToJSON(value?: ActionResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'action': value.action,
        'relations': value.relations === undefined ? undefined : ((value.relations as Array<any>).map(RelationResponseToJSON)),
    };
}

