/* tslint:disable */
/* eslint-disable */
/**
 * sudosos-back-end
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthenticationResetTokenRequest
 */
export interface AuthenticationResetTokenRequest {
    /**
     * The mail of the user
     * @type {string}
     * @memberof AuthenticationResetTokenRequest
     */
    accountMail: string;
    /**
     * The reset token passcode
     * @type {string}
     * @memberof AuthenticationResetTokenRequest
     */
    token: string;
    /**
     * The new password to set
     * @type {string}
     * @memberof AuthenticationResetTokenRequest
     */
    password: string;
}

/**
 * Check if a given object implements the AuthenticationResetTokenRequest interface.
 */
export function instanceOfAuthenticationResetTokenRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "accountMail" in value;
    isInstance = isInstance && "token" in value;
    isInstance = isInstance && "password" in value;

    return isInstance;
}

export function AuthenticationResetTokenRequestFromJSON(json: any): AuthenticationResetTokenRequest {
    return AuthenticationResetTokenRequestFromJSONTyped(json, false);
}

export function AuthenticationResetTokenRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthenticationResetTokenRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'accountMail': json['accountMail'],
        'token': json['token'],
        'password': json['password'],
    };
}

export function AuthenticationResetTokenRequestToJSON(value?: AuthenticationResetTokenRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'accountMail': value.accountMail,
        'token': value.token,
        'password': value.password,
    };
}

