/* tslint:disable */
/* eslint-disable */
/**
 * sudosos-back-end
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthenticationLocalRequest
 */
export interface AuthenticationLocalRequest {
    /**
     * The users mail to authenticate
     * @type {string}
     * @memberof AuthenticationLocalRequest
     */
    accountMail: string;
    /**
     * The password
     * @type {string}
     * @memberof AuthenticationLocalRequest
     */
    password: string;
}

/**
 * Check if a given object implements the AuthenticationLocalRequest interface.
 */
export function instanceOfAuthenticationLocalRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "accountMail" in value;
    isInstance = isInstance && "password" in value;

    return isInstance;
}

export function AuthenticationLocalRequestFromJSON(json: any): AuthenticationLocalRequest {
    return AuthenticationLocalRequestFromJSONTyped(json, false);
}

export function AuthenticationLocalRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthenticationLocalRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'accountMail': json['accountMail'],
        'password': json['password'],
    };
}

export function AuthenticationLocalRequestToJSON(value?: AuthenticationLocalRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'accountMail': value.accountMail,
        'password': value.password,
    };
}

