/* tslint:disable */
/* eslint-disable */
/**
 * sudosos-back-end
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthenticationNfcRequest
 */
export interface AuthenticationNfcRequest {
    /**
     * 
     * @type {string}
     * @memberof AuthenticationNfcRequest
     */
    nfcCode: string;
}

/**
 * Check if a given object implements the AuthenticationNfcRequest interface.
 */
export function instanceOfAuthenticationNfcRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "nfcCode" in value;

    return isInstance;
}

export function AuthenticationNfcRequestFromJSON(json: any): AuthenticationNfcRequest {
    return AuthenticationNfcRequestFromJSONTyped(json, false);
}

export function AuthenticationNfcRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthenticationNfcRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'nfcCode': json['nfcCode'],
    };
}

export function AuthenticationNfcRequestToJSON(value?: AuthenticationNfcRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'nfcCode': value.nfcCode,
    };
}

