/* tslint:disable */
/* eslint-disable */
/**
 * sudosos-back-end
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthenticationKeyRequest
 */
export interface AuthenticationKeyRequest {
    /**
     * 
     * @type {number}
     * @memberof AuthenticationKeyRequest
     */
    userId: number;
    /**
     * The password
     * @type {string}
     * @memberof AuthenticationKeyRequest
     */
    key: string;
}

/**
 * Check if a given object implements the AuthenticationKeyRequest interface.
 */
export function instanceOfAuthenticationKeyRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "userId" in value;
    isInstance = isInstance && "key" in value;

    return isInstance;
}

export function AuthenticationKeyRequestFromJSON(json: any): AuthenticationKeyRequest {
    return AuthenticationKeyRequestFromJSONTyped(json, false);
}

export function AuthenticationKeyRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthenticationKeyRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'userId': json['userId'],
        'key': json['key'],
    };
}

export function AuthenticationKeyRequestToJSON(value?: AuthenticationKeyRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'userId': value.userId,
        'key': value.key,
    };
}

