/* tslint:disable */
/* eslint-disable */
/**
 * sudosos-back-end
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthenticationLDAPRequest
 */
export interface AuthenticationLDAPRequest {
    /**
     * The AD account name to authenticate
     * @type {string}
     * @memberof AuthenticationLDAPRequest
     */
    accountName: string;
    /**
     * The password
     * @type {string}
     * @memberof AuthenticationLDAPRequest
     */
    password: string;
}

/**
 * Check if a given object implements the AuthenticationLDAPRequest interface.
 */
export function instanceOfAuthenticationLDAPRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "accountName" in value;
    isInstance = isInstance && "password" in value;

    return isInstance;
}

export function AuthenticationLDAPRequestFromJSON(json: any): AuthenticationLDAPRequest {
    return AuthenticationLDAPRequestFromJSONTyped(json, false);
}

export function AuthenticationLDAPRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthenticationLDAPRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'accountName': json['accountName'],
        'password': json['password'],
    };
}

export function AuthenticationLDAPRequestToJSON(value?: AuthenticationLDAPRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'accountName': value.accountName,
        'password': value.password,
    };
}

