/* tslint:disable */
/* eslint-disable */
/**
 * sudosos-back-end
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthenticationMockRequest
 */
export interface AuthenticationMockRequest {
    /**
     * 
     * @type {number}
     * @memberof AuthenticationMockRequest
     */
    userId: number;
    /**
     * 
     * @type {string}
     * @memberof AuthenticationMockRequest
     */
    nonce: string;
}

/**
 * Check if a given object implements the AuthenticationMockRequest interface.
 */
export function instanceOfAuthenticationMockRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "userId" in value;
    isInstance = isInstance && "nonce" in value;

    return isInstance;
}

export function AuthenticationMockRequestFromJSON(json: any): AuthenticationMockRequest {
    return AuthenticationMockRequestFromJSONTyped(json, false);
}

export function AuthenticationMockRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthenticationMockRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'userId': json['userId'],
        'nonce': json['nonce'],
    };
}

export function AuthenticationMockRequestToJSON(value?: AuthenticationMockRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'userId': value.userId,
        'nonce': value.nonce,
    };
}

