/* tslint:disable */
/* eslint-disable */
/**
 * sudosos-back-end
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BannerImage
 */
export interface BannerImage {
    /**
     * The creation date of the object.
     * @type {string}
     * @memberof BannerImage
     */
    createdAt?: string;
    /**
     * The last update date of the object.
     * @type {string}
     * @memberof BannerImage
     */
    updatedAt?: string;
    /**
     * The current version of the object.
     * @type {number}
     * @memberof BannerImage
     */
    version?: number;
}

/**
 * Check if a given object implements the BannerImage interface.
 */
export function instanceOfBannerImage(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function BannerImageFromJSON(json: any): BannerImage {
    return BannerImageFromJSONTyped(json, false);
}

export function BannerImageFromJSONTyped(json: any, ignoreDiscriminator: boolean): BannerImage {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'createdAt': !exists(json, 'createdAt') ? undefined : json['createdAt'],
        'updatedAt': !exists(json, 'updatedAt') ? undefined : json['updatedAt'],
        'version': !exists(json, 'version') ? undefined : json['version'],
    };
}

export function BannerImageToJSON(value?: BannerImage | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'createdAt': value.createdAt,
        'updatedAt': value.updatedAt,
        'version': value.version,
    };
}

