/* tslint:disable */
/* eslint-disable */
/**
 * sudosos-back-end
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BasePointOfSale
 */
export interface BasePointOfSale {
    /**
     * The unique name of the pointOfSale.
     * @type {string}
     * @memberof BasePointOfSale
     */
    name: string;
    /**
     * The creation date of the object.
     * @type {string}
     * @memberof BasePointOfSale
     */
    createdAt?: string;
    /**
     * The last update date of the object.
     * @type {string}
     * @memberof BasePointOfSale
     */
    updatedAt?: string;
    /**
     * The current version of the object.
     * @type {number}
     * @memberof BasePointOfSale
     */
    version?: number;
}

/**
 * Check if a given object implements the BasePointOfSale interface.
 */
export function instanceOfBasePointOfSale(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;

    return isInstance;
}

export function BasePointOfSaleFromJSON(json: any): BasePointOfSale {
    return BasePointOfSaleFromJSONTyped(json, false);
}

export function BasePointOfSaleFromJSONTyped(json: any, ignoreDiscriminator: boolean): BasePointOfSale {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'createdAt': !exists(json, 'createdAt') ? undefined : json['createdAt'],
        'updatedAt': !exists(json, 'updatedAt') ? undefined : json['updatedAt'],
        'version': !exists(json, 'version') ? undefined : json['version'],
    };
}

export function BasePointOfSaleToJSON(value?: BasePointOfSale | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'createdAt': value.createdAt,
        'updatedAt': value.updatedAt,
        'version': value.version,
    };
}

