/* tslint:disable */
/* eslint-disable */
/**
 * sudosos-back-end
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { BasePointOfSaleResponse } from './BasePointOfSaleResponse';
import {
    BasePointOfSaleResponseFromJSON,
    BasePointOfSaleResponseFromJSONTyped,
    BasePointOfSaleResponseToJSON,
} from './BasePointOfSaleResponse';
import type { Dinero } from './Dinero';
import {
    DineroFromJSON,
    DineroFromJSONTyped,
    DineroToJSON,
} from './Dinero';
import type { UserResponse } from './UserResponse';
import {
    UserResponseFromJSON,
    UserResponseFromJSONTyped,
    UserResponseToJSON,
} from './UserResponse';

/**
 * 
 * @export
 * @interface BaseTransactionResponse
 */
export interface BaseTransactionResponse {
    /**
     * 
     * @type {UserResponse}
     * @memberof BaseTransactionResponse
     */
    from: UserResponse;
    /**
     * 
     * @type {UserResponse}
     * @memberof BaseTransactionResponse
     */
    createdBy?: UserResponse;
    /**
     * 
     * @type {BasePointOfSaleResponse}
     * @memberof BaseTransactionResponse
     */
    pointOfSale?: BasePointOfSaleResponse;
    /**
     * 
     * @type {Dinero}
     * @memberof BaseTransactionResponse
     */
    value?: Dinero;
    /**
     * The unique id of the entity.
     * @type {number}
     * @memberof BaseTransactionResponse
     */
    id: number;
    /**
     * The creation Date of the entity.
     * @type {string}
     * @memberof BaseTransactionResponse
     */
    createdAt?: string;
    /**
     * The last update Date of the entity.
     * @type {string}
     * @memberof BaseTransactionResponse
     */
    updatedAt?: string;
    /**
     * The version of the entity.
     * @type {number}
     * @memberof BaseTransactionResponse
     */
    version?: number;
}

/**
 * Check if a given object implements the BaseTransactionResponse interface.
 */
export function instanceOfBaseTransactionResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "from" in value;
    isInstance = isInstance && "id" in value;

    return isInstance;
}

export function BaseTransactionResponseFromJSON(json: any): BaseTransactionResponse {
    return BaseTransactionResponseFromJSONTyped(json, false);
}

export function BaseTransactionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BaseTransactionResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'from': UserResponseFromJSON(json['from']),
        'createdBy': !exists(json, 'createdBy') ? undefined : UserResponseFromJSON(json['createdBy']),
        'pointOfSale': !exists(json, 'pointOfSale') ? undefined : BasePointOfSaleResponseFromJSON(json['pointOfSale']),
        'value': !exists(json, 'value') ? undefined : DineroFromJSON(json['value']),
        'id': json['id'],
        'createdAt': !exists(json, 'createdAt') ? undefined : json['createdAt'],
        'updatedAt': !exists(json, 'updatedAt') ? undefined : json['updatedAt'],
        'version': !exists(json, 'version') ? undefined : json['version'],
    };
}

export function BaseTransactionResponseToJSON(value?: BaseTransactionResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'from': UserResponseToJSON(value.from),
        'createdBy': UserResponseToJSON(value.createdBy),
        'pointOfSale': BasePointOfSaleResponseToJSON(value.pointOfSale),
        'value': DineroToJSON(value.value),
        'id': value.id,
        'createdAt': value.createdAt,
        'updatedAt': value.updatedAt,
        'version': value.version,
    };
}

