/* tslint:disable */
/* eslint-disable */
/**
 * sudosos-back-end
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BaseEntityWithoutId
 */
export interface BaseEntityWithoutId {
    /**
     * The creation date of the object.
     * @type {string}
     * @memberof BaseEntityWithoutId
     */
    createdAt?: string;
    /**
     * The last update date of the object.
     * @type {string}
     * @memberof BaseEntityWithoutId
     */
    updatedAt?: string;
    /**
     * The current version of the object.
     * @type {number}
     * @memberof BaseEntityWithoutId
     */
    version?: number;
}

/**
 * Check if a given object implements the BaseEntityWithoutId interface.
 */
export function instanceOfBaseEntityWithoutId(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function BaseEntityWithoutIdFromJSON(json: any): BaseEntityWithoutId {
    return BaseEntityWithoutIdFromJSONTyped(json, false);
}

export function BaseEntityWithoutIdFromJSONTyped(json: any, ignoreDiscriminator: boolean): BaseEntityWithoutId {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'createdAt': !exists(json, 'createdAt') ? undefined : json['createdAt'],
        'updatedAt': !exists(json, 'updatedAt') ? undefined : json['updatedAt'],
        'version': !exists(json, 'version') ? undefined : json['version'],
    };
}

export function BaseEntityWithoutIdToJSON(value?: BaseEntityWithoutId | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'createdAt': value.createdAt,
        'updatedAt': value.updatedAt,
        'version': value.version,
    };
}

