/* tslint:disable */
/* eslint-disable */
/**
 * sudosos-back-end
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { BaseVatGroupResponse } from './BaseVatGroupResponse';
import {
    BaseVatGroupResponseFromJSON,
    BaseVatGroupResponseFromJSONTyped,
    BaseVatGroupResponseToJSON,
} from './BaseVatGroupResponse';
import type { DineroObjectResponse } from './DineroObjectResponse';
import {
    DineroObjectResponseFromJSON,
    DineroObjectResponseFromJSONTyped,
    DineroObjectResponseToJSON,
} from './DineroObjectResponse';

/**
 * 
 * @export
 * @interface BaseProductResponse
 */
export interface BaseProductResponse {
    /**
     * The name of the product.
     * @type {string}
     * @memberof BaseProductResponse
     */
    name: string;
    /**
     * 
     * @type {DineroObjectResponse}
     * @memberof BaseProductResponse
     */
    priceInclVat: DineroObjectResponse;
    /**
     * 
     * @type {BaseVatGroupResponse}
     * @memberof BaseProductResponse
     */
    vat: BaseVatGroupResponse;
    /**
     * The unique id of the entity.
     * @type {number}
     * @memberof BaseProductResponse
     */
    id: number;
    /**
     * The creation Date of the entity.
     * @type {string}
     * @memberof BaseProductResponse
     */
    createdAt?: string;
    /**
     * The last update Date of the entity.
     * @type {string}
     * @memberof BaseProductResponse
     */
    updatedAt?: string;
    /**
     * The version of the entity.
     * @type {number}
     * @memberof BaseProductResponse
     */
    version?: number;
}

/**
 * Check if a given object implements the BaseProductResponse interface.
 */
export function instanceOfBaseProductResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "priceInclVat" in value;
    isInstance = isInstance && "vat" in value;
    isInstance = isInstance && "id" in value;

    return isInstance;
}

export function BaseProductResponseFromJSON(json: any): BaseProductResponse {
    return BaseProductResponseFromJSONTyped(json, false);
}

export function BaseProductResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BaseProductResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'priceInclVat': DineroObjectResponseFromJSON(json['priceInclVat']),
        'vat': BaseVatGroupResponseFromJSON(json['vat']),
        'id': json['id'],
        'createdAt': !exists(json, 'createdAt') ? undefined : json['createdAt'],
        'updatedAt': !exists(json, 'updatedAt') ? undefined : json['updatedAt'],
        'version': !exists(json, 'version') ? undefined : json['version'],
    };
}

export function BaseProductResponseToJSON(value?: BaseProductResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'priceInclVat': DineroObjectResponseToJSON(value.priceInclVat),
        'vat': BaseVatGroupResponseToJSON(value.vat),
        'id': value.id,
        'createdAt': value.createdAt,
        'updatedAt': value.updatedAt,
        'version': value.version,
    };
}

