/* tslint:disable */
/* eslint-disable */
/**
 * sudosos-back-end
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BaseEntity
 */
export interface BaseEntity {
    /**
     * The auto-generated object id.
     * @type {number}
     * @memberof BaseEntity
     */
    id: number;
    /**
     * The creation date of the object.
     * @type {string}
     * @memberof BaseEntity
     */
    createdAt?: string;
    /**
     * The last update date of the object.
     * @type {string}
     * @memberof BaseEntity
     */
    updatedAt?: string;
    /**
     * The current version of the object.
     * @type {number}
     * @memberof BaseEntity
     */
    version?: number;
}

/**
 * Check if a given object implements the BaseEntity interface.
 */
export function instanceOfBaseEntity(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;

    return isInstance;
}

export function BaseEntityFromJSON(json: any): BaseEntity {
    return BaseEntityFromJSONTyped(json, false);
}

export function BaseEntityFromJSONTyped(json: any, ignoreDiscriminator: boolean): BaseEntity {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'createdAt': !exists(json, 'createdAt') ? undefined : json['createdAt'],
        'updatedAt': !exists(json, 'updatedAt') ? undefined : json['updatedAt'],
        'version': !exists(json, 'version') ? undefined : json['version'],
    };
}

export function BaseEntityToJSON(value?: BaseEntity | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'createdAt': value.createdAt,
        'updatedAt': value.updatedAt,
        'version': value.version,
    };
}

