/* tslint:disable */
/* eslint-disable */
/**
 * sudosos-back-end
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { BaseUserResponse } from './BaseUserResponse';
import {
    BaseUserResponseFromJSON,
    BaseUserResponseFromJSONTyped,
    BaseUserResponseToJSON,
} from './BaseUserResponse';
import type { DineroObjectResponse } from './DineroObjectResponse';
import {
    DineroObjectResponseFromJSON,
    DineroObjectResponseFromJSONTyped,
    DineroObjectResponseToJSON,
} from './DineroObjectResponse';

/**
 * 
 * @export
 * @interface BoilerPayoutRequestResponse
 */
export interface BoilerPayoutRequestResponse {
    /**
     * 
     * @type {BaseUserResponse}
     * @memberof BoilerPayoutRequestResponse
     */
    requestedBy: BaseUserResponse;
    /**
     * 
     * @type {BaseUserResponse}
     * @memberof BoilerPayoutRequestResponse
     */
    approvedBy?: BaseUserResponse;
    /**
     * 
     * @type {DineroObjectResponse}
     * @memberof BoilerPayoutRequestResponse
     */
    amount: DineroObjectResponse;
    /**
     * The unique id of the entity.
     * @type {number}
     * @memberof BoilerPayoutRequestResponse
     */
    id: number;
    /**
     * The creation Date of the entity.
     * @type {string}
     * @memberof BoilerPayoutRequestResponse
     */
    createdAt?: string;
    /**
     * The last update Date of the entity.
     * @type {string}
     * @memberof BoilerPayoutRequestResponse
     */
    updatedAt?: string;
    /**
     * The version of the entity.
     * @type {number}
     * @memberof BoilerPayoutRequestResponse
     */
    version?: number;
}

/**
 * Check if a given object implements the BoilerPayoutRequestResponse interface.
 */
export function instanceOfBoilerPayoutRequestResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "requestedBy" in value;
    isInstance = isInstance && "amount" in value;
    isInstance = isInstance && "id" in value;

    return isInstance;
}

export function BoilerPayoutRequestResponseFromJSON(json: any): BoilerPayoutRequestResponse {
    return BoilerPayoutRequestResponseFromJSONTyped(json, false);
}

export function BoilerPayoutRequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BoilerPayoutRequestResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'requestedBy': BaseUserResponseFromJSON(json['requestedBy']),
        'approvedBy': !exists(json, 'approvedBy') ? undefined : BaseUserResponseFromJSON(json['approvedBy']),
        'amount': DineroObjectResponseFromJSON(json['amount']),
        'id': json['id'],
        'createdAt': !exists(json, 'createdAt') ? undefined : json['createdAt'],
        'updatedAt': !exists(json, 'updatedAt') ? undefined : json['updatedAt'],
        'version': !exists(json, 'version') ? undefined : json['version'],
    };
}

export function BoilerPayoutRequestResponseToJSON(value?: BoilerPayoutRequestResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'requestedBy': BaseUserResponseToJSON(value.requestedBy),
        'approvedBy': BaseUserResponseToJSON(value.approvedBy),
        'amount': DineroObjectResponseToJSON(value.amount),
        'id': value.id,
        'createdAt': value.createdAt,
        'updatedAt': value.updatedAt,
        'version': value.version,
    };
}

