/* tslint:disable */
/* eslint-disable */
/**
 * sudosos-back-end
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { BaseUserResponse } from './BaseUserResponse';
import {
    BaseUserResponseFromJSON,
    BaseUserResponseFromJSONTyped,
    BaseUserResponseToJSON,
} from './BaseUserResponse';

/**
 * 
 * @export
 * @interface ContainerResponse
 */
export interface ContainerResponse {
    /**
     * 
     * @type {BaseUserResponse}
     * @memberof ContainerResponse
     */
    owner: BaseUserResponse;
    /**
     * The unique id of the entity.
     * @type {number}
     * @memberof ContainerResponse
     */
    id: number;
    /**
     * The creation Date of the entity.
     * @type {string}
     * @memberof ContainerResponse
     */
    createdAt?: string;
    /**
     * The last update Date of the entity.
     * @type {string}
     * @memberof ContainerResponse
     */
    updatedAt?: string;
    /**
     * The version of the entity.
     * @type {number}
     * @memberof ContainerResponse
     */
    version?: number;
}

/**
 * Check if a given object implements the ContainerResponse interface.
 */
export function instanceOfContainerResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "owner" in value;
    isInstance = isInstance && "id" in value;

    return isInstance;
}

export function ContainerResponseFromJSON(json: any): ContainerResponse {
    return ContainerResponseFromJSONTyped(json, false);
}

export function ContainerResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContainerResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'owner': BaseUserResponseFromJSON(json['owner']),
        'id': json['id'],
        'createdAt': !exists(json, 'createdAt') ? undefined : json['createdAt'],
        'updatedAt': !exists(json, 'updatedAt') ? undefined : json['updatedAt'],
        'version': !exists(json, 'version') ? undefined : json['version'],
    };
}

export function ContainerResponseToJSON(value?: ContainerResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'owner': BaseUserResponseToJSON(value.owner),
        'id': value.id,
        'createdAt': value.createdAt,
        'updatedAt': value.updatedAt,
        'version': value.version,
    };
}

