/* tslint:disable */
/* eslint-disable */
/**
 * sudosos-back-end
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreatePointOfSaleRequest
 */
export interface CreatePointOfSaleRequest {
    /**
     * Name of the POS
     * @type {string}
     * @memberof CreatePointOfSaleRequest
     */
    name: string;
    /**
     * Whether this POS requires users to
     * authenticate themselves before making a transaction
     * @type {boolean}
     * @memberof CreatePointOfSaleRequest
     */
    useAuthentication: boolean;
    /**
     * 
     * @type {Array<number>}
     * @memberof CreatePointOfSaleRequest
     */
    containers?: Array<number>;
    /**
     * ID of the user who will own the POS, if undefined it will
     *    default to the token ID.
     * @type {number}
     * @memberof CreatePointOfSaleRequest
     */
    ownerId?: number;
}

/**
 * Check if a given object implements the CreatePointOfSaleRequest interface.
 */
export function instanceOfCreatePointOfSaleRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "useAuthentication" in value;

    return isInstance;
}

export function CreatePointOfSaleRequestFromJSON(json: any): CreatePointOfSaleRequest {
    return CreatePointOfSaleRequestFromJSONTyped(json, false);
}

export function CreatePointOfSaleRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreatePointOfSaleRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'useAuthentication': json['useAuthentication'],
        'containers': !exists(json, 'containers') ? undefined : json['containers'],
        'ownerId': !exists(json, 'ownerId') ? undefined : json['ownerId'],
    };
}

export function CreatePointOfSaleRequestToJSON(value?: CreatePointOfSaleRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'useAuthentication': value.useAuthentication,
        'containers': value.containers,
        'ownerId': value.ownerId,
    };
}

