/* tslint:disable */
/* eslint-disable */
/**
 * sudosos-back-end
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateContainerRequest
 */
export interface CreateContainerRequest {
    /**
     * Name of the container
     * @type {string}
     * @memberof CreateContainerRequest
     */
    name: string;
    /**
     * 
     * @type {Array<number>}
     * @memberof CreateContainerRequest
     */
    products: Array<number>;
    /**
     * Whether the container is public or not
     * @type {boolean}
     * @memberof CreateContainerRequest
     */
    _public: boolean;
    /**
     * Id of the user who will own the container, if undefined it will
     *    default to the token ID.
     * @type {number}
     * @memberof CreateContainerRequest
     */
    ownerId?: number;
}

/**
 * Check if a given object implements the CreateContainerRequest interface.
 */
export function instanceOfCreateContainerRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "products" in value;
    isInstance = isInstance && "_public" in value;

    return isInstance;
}

export function CreateContainerRequestFromJSON(json: any): CreateContainerRequest {
    return CreateContainerRequestFromJSONTyped(json, false);
}

export function CreateContainerRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateContainerRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'products': json['products'],
        '_public': json['public'],
        'ownerId': !exists(json, 'ownerId') ? undefined : json['ownerId'],
    };
}

export function CreateContainerRequestToJSON(value?: CreateContainerRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'products': value.products,
        'public': value._public,
        'ownerId': value.ownerId,
    };
}

