/* tslint:disable */
/* eslint-disable */
/**
 * sudosos-back-end
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { DineroObjectRequest } from './DineroObjectRequest';
import {
    DineroObjectRequestFromJSON,
    DineroObjectRequestFromJSONTyped,
    DineroObjectRequestToJSON,
} from './DineroObjectRequest';

/**
 * 
 * @export
 * @interface CreateProductRequest
 */
export interface CreateProductRequest {
    /**
     * Name of the product
     * @type {string}
     * @memberof CreateProductRequest
     */
    name: string;
    /**
     * 
     * @type {DineroObjectRequest}
     * @memberof CreateProductRequest
     */
    priceInclVat: DineroObjectRequest;
    /**
     * VAT group ID of the product
     * @type {number}
     * @memberof CreateProductRequest
     */
    vat: number;
    /**
     * Category of the product
     * @type {number}
     * @memberof CreateProductRequest
     */
    category: number;
    /**
     * Alcohol percentage of the product in 2 decimals
     * @type {number}
     * @memberof CreateProductRequest
     */
    alcoholPercentage: number;
    /**
     * ID of the owner
     * @type {number}
     * @memberof CreateProductRequest
     */
    ownerId: number;
}

/**
 * Check if a given object implements the CreateProductRequest interface.
 */
export function instanceOfCreateProductRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "priceInclVat" in value;
    isInstance = isInstance && "vat" in value;
    isInstance = isInstance && "category" in value;
    isInstance = isInstance && "alcoholPercentage" in value;
    isInstance = isInstance && "ownerId" in value;

    return isInstance;
}

export function CreateProductRequestFromJSON(json: any): CreateProductRequest {
    return CreateProductRequestFromJSONTyped(json, false);
}

export function CreateProductRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateProductRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'priceInclVat': DineroObjectRequestFromJSON(json['priceInclVat']),
        'vat': json['vat'],
        'category': json['category'],
        'alcoholPercentage': json['alcoholPercentage'],
        'ownerId': json['ownerId'],
    };
}

export function CreateProductRequestToJSON(value?: CreateProductRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'priceInclVat': DineroObjectRequestToJSON(value.priceInclVat),
        'vat': value.vat,
        'category': value.category,
        'alcoholPercentage': value.alcoholPercentage,
        'ownerId': value.ownerId,
    };
}

