/* tslint:disable */
/* eslint-disable */
/**
 * sudosos-back-end
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DineroObject
 */
export interface DineroObject {
    /**
     * amount
     * @type {number}
     * @memberof DineroObject
     */
    amount: number;
    /**
     * currency
     * @type {string}
     * @memberof DineroObject
     */
    currency: string;
    /**
     * precision
     * @type {number}
     * @memberof DineroObject
     */
    precision: number;
}

/**
 * Check if a given object implements the DineroObject interface.
 */
export function instanceOfDineroObject(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "amount" in value;
    isInstance = isInstance && "currency" in value;
    isInstance = isInstance && "precision" in value;

    return isInstance;
}

export function DineroObjectFromJSON(json: any): DineroObject {
    return DineroObjectFromJSONTyped(json, false);
}

export function DineroObjectFromJSONTyped(json: any, ignoreDiscriminator: boolean): DineroObject {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'amount': json['amount'],
        'currency': json['currency'],
        'precision': json['precision'],
    };
}

export function DineroObjectToJSON(value?: DineroObject | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'amount': value.amount,
        'currency': value.currency,
        'precision': value.precision,
    };
}

