/* tslint:disable */
/* eslint-disable */
/**
 * sudosos-back-end
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EanAuthenticator
 */
export interface EanAuthenticator {
    /**
     * The EAN code
     * @type {string}
     * @memberof EanAuthenticator
     */
    eanCode: string;
    /**
     * The creation date of the object.
     * @type {string}
     * @memberof EanAuthenticator
     */
    createdAt?: string;
    /**
     * The last update date of the object.
     * @type {string}
     * @memberof EanAuthenticator
     */
    updatedAt?: string;
    /**
     * The current version of the object.
     * @type {number}
     * @memberof EanAuthenticator
     */
    version?: number;
}

/**
 * Check if a given object implements the EanAuthenticator interface.
 */
export function instanceOfEanAuthenticator(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "eanCode" in value;

    return isInstance;
}

export function EanAuthenticatorFromJSON(json: any): EanAuthenticator {
    return EanAuthenticatorFromJSONTyped(json, false);
}

export function EanAuthenticatorFromJSONTyped(json: any, ignoreDiscriminator: boolean): EanAuthenticator {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'eanCode': json['eanCode'],
        'createdAt': !exists(json, 'createdAt') ? undefined : json['createdAt'],
        'updatedAt': !exists(json, 'updatedAt') ? undefined : json['updatedAt'],
        'version': !exists(json, 'version') ? undefined : json['version'],
    };
}

export function EanAuthenticatorToJSON(value?: EanAuthenticator | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'eanCode': value.eanCode,
        'createdAt': value.createdAt,
        'updatedAt': value.updatedAt,
        'version': value.version,
    };
}

