/* tslint:disable */
/* eslint-disable */
/**
 * sudosos-back-end
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GEWISAuthenticationPinRequest
 */
export interface GEWISAuthenticationPinRequest {
    /**
     * 
     * @type {number}
     * @memberof GEWISAuthenticationPinRequest
     */
    gewisId: number;
    /**
     * 
     * @type {string}
     * @memberof GEWISAuthenticationPinRequest
     */
    pin: string;
}

/**
 * Check if a given object implements the GEWISAuthenticationPinRequest interface.
 */
export function instanceOfGEWISAuthenticationPinRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "gewisId" in value;
    isInstance = isInstance && "pin" in value;

    return isInstance;
}

export function GEWISAuthenticationPinRequestFromJSON(json: any): GEWISAuthenticationPinRequest {
    return GEWISAuthenticationPinRequestFromJSONTyped(json, false);
}

export function GEWISAuthenticationPinRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): GEWISAuthenticationPinRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'gewisId': json['gewisId'],
        'pin': json['pin'],
    };
}

export function GEWISAuthenticationPinRequestToJSON(value?: GEWISAuthenticationPinRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'gewisId': value.gewisId,
        'pin': value.pin,
    };
}

