/* tslint:disable */
/* eslint-disable */
/**
 * sudosos-back-end
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HashBasedAuthenticationMethod
 */
export interface HashBasedAuthenticationMethod {
    /**
     * The hash of the authentication
     * @type {string}
     * @memberof HashBasedAuthenticationMethod
     */
    hash: string;
    /**
     * The creation date of the object.
     * @type {string}
     * @memberof HashBasedAuthenticationMethod
     */
    createdAt?: string;
    /**
     * The last update date of the object.
     * @type {string}
     * @memberof HashBasedAuthenticationMethod
     */
    updatedAt?: string;
    /**
     * The current version of the object.
     * @type {number}
     * @memberof HashBasedAuthenticationMethod
     */
    version?: number;
}

/**
 * Check if a given object implements the HashBasedAuthenticationMethod interface.
 */
export function instanceOfHashBasedAuthenticationMethod(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "hash" in value;

    return isInstance;
}

export function HashBasedAuthenticationMethodFromJSON(json: any): HashBasedAuthenticationMethod {
    return HashBasedAuthenticationMethodFromJSONTyped(json, false);
}

export function HashBasedAuthenticationMethodFromJSONTyped(json: any, ignoreDiscriminator: boolean): HashBasedAuthenticationMethod {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'hash': json['hash'],
        'createdAt': !exists(json, 'createdAt') ? undefined : json['createdAt'],
        'updatedAt': !exists(json, 'updatedAt') ? undefined : json['updatedAt'],
        'version': !exists(json, 'version') ? undefined : json['version'],
    };
}

export function HashBasedAuthenticationMethodToJSON(value?: HashBasedAuthenticationMethod | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'hash': value.hash,
        'createdAt': value.createdAt,
        'updatedAt': value.updatedAt,
        'version': value.version,
    };
}

