/* tslint:disable */
/* eslint-disable */
/**
 * sudosos-back-end
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { User } from './User';
import {
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
} from './User';

/**
 * 
 * @export
 * @interface InvoiceUser
 */
export interface InvoiceUser {
    /**
     * 
     * @type {User}
     * @memberof InvoiceUser
     */
    user: User;
    /**
     * Whether the user gets automatic invoices
     * @type {boolean}
     * @memberof InvoiceUser
     */
    automatic?: boolean;
    /**
     * The creation date of the object.
     * @type {string}
     * @memberof InvoiceUser
     */
    createdAt?: string;
    /**
     * The last update date of the object.
     * @type {string}
     * @memberof InvoiceUser
     */
    updatedAt?: string;
    /**
     * The current version of the object.
     * @type {number}
     * @memberof InvoiceUser
     */
    version?: number;
}

/**
 * Check if a given object implements the InvoiceUser interface.
 */
export function instanceOfInvoiceUser(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "user" in value;

    return isInstance;
}

export function InvoiceUserFromJSON(json: any): InvoiceUser {
    return InvoiceUserFromJSONTyped(json, false);
}

export function InvoiceUserFromJSONTyped(json: any, ignoreDiscriminator: boolean): InvoiceUser {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'user': UserFromJSON(json['user']),
        'automatic': !exists(json, 'automatic') ? undefined : json['automatic'],
        'createdAt': !exists(json, 'createdAt') ? undefined : json['createdAt'],
        'updatedAt': !exists(json, 'updatedAt') ? undefined : json['updatedAt'],
        'version': !exists(json, 'version') ? undefined : json['version'],
    };
}

export function InvoiceUserToJSON(value?: InvoiceUser | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'user': UserToJSON(value.user),
        'automatic': value.automatic,
        'createdAt': value.createdAt,
        'updatedAt': value.updatedAt,
        'version': value.version,
    };
}

