/* tslint:disable */
/* eslint-disable */
/**
 * sudosos-back-end
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { BaseUserResponse } from './BaseUserResponse';
import {
    BaseUserResponseFromJSON,
    BaseUserResponseFromJSONTyped,
    BaseUserResponseToJSON,
} from './BaseUserResponse';

/**
 * 
 * @export
 * @interface InvoiceStatusResponse
 */
export interface InvoiceStatusResponse {
    /**
     * 
     * @type {BaseUserResponse}
     * @memberof InvoiceStatusResponse
     */
    changedBy: BaseUserResponse;
    /**
     * The state of the invoice,
     * can be either CREATED, SENT, PAID or DELETED.
     * @type {string}
     * @memberof InvoiceStatusResponse
     */
    state: string;
}

/**
 * Check if a given object implements the InvoiceStatusResponse interface.
 */
export function instanceOfInvoiceStatusResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "changedBy" in value;
    isInstance = isInstance && "state" in value;

    return isInstance;
}

export function InvoiceStatusResponseFromJSON(json: any): InvoiceStatusResponse {
    return InvoiceStatusResponseFromJSONTyped(json, false);
}

export function InvoiceStatusResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): InvoiceStatusResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'changedBy': BaseUserResponseFromJSON(json['changedBy']),
        'state': json['state'],
    };
}

export function InvoiceStatusResponseToJSON(value?: InvoiceStatusResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'changedBy': BaseUserResponseToJSON(value.changedBy),
        'state': value.state,
    };
}

