/* tslint:disable */
/* eslint-disable */
/**
 * sudosos-back-end
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { DineroObject } from './DineroObject';
import {
    DineroObjectFromJSON,
    DineroObjectFromJSONTyped,
    DineroObjectToJSON,
} from './DineroObject';

/**
 * 
 * @export
 * @interface InvoiceEntryResponse
 */
export interface InvoiceEntryResponse {
    /**
     * The description of the entry
     * @type {string}
     * @memberof InvoiceEntryResponse
     */
    description: string;
    /**
     * Amount of products sold.
     * @type {number}
     * @memberof InvoiceEntryResponse
     */
    amount: number;
    /**
     * 
     * @type {DineroObject}
     * @memberof InvoiceEntryResponse
     */
    priceInclVat: DineroObject;
    /**
     * The percentage of VAT applied to this entry
     * @type {number}
     * @memberof InvoiceEntryResponse
     */
    vatPercentage: number;
}

/**
 * Check if a given object implements the InvoiceEntryResponse interface.
 */
export function instanceOfInvoiceEntryResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "description" in value;
    isInstance = isInstance && "amount" in value;
    isInstance = isInstance && "priceInclVat" in value;
    isInstance = isInstance && "vatPercentage" in value;

    return isInstance;
}

export function InvoiceEntryResponseFromJSON(json: any): InvoiceEntryResponse {
    return InvoiceEntryResponseFromJSONTyped(json, false);
}

export function InvoiceEntryResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): InvoiceEntryResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'description': json['description'],
        'amount': json['amount'],
        'priceInclVat': DineroObjectFromJSON(json['priceInclVat']),
        'vatPercentage': json['vatPercentage'],
    };
}

export function InvoiceEntryResponseToJSON(value?: InvoiceEntryResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'description': value.description,
        'amount': value.amount,
        'priceInclVat': DineroObjectToJSON(value.priceInclVat),
        'vatPercentage': value.vatPercentage,
    };
}

