/* tslint:disable */
/* eslint-disable */
/**
 * sudosos-back-end
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Dinero } from './Dinero';
import {
    DineroFromJSON,
    DineroFromJSONTyped,
    DineroToJSON,
} from './Dinero';
import type { Invoice } from './Invoice';
import {
    InvoiceFromJSON,
    InvoiceFromJSONTyped,
    InvoiceToJSON,
} from './Invoice';

/**
 * 
 * @export
 * @interface InvoiceEntry
 */
export interface InvoiceEntry {
    /**
     * 
     * @type {Invoice}
     * @memberof InvoiceEntry
     */
    invoice: Invoice;
    /**
     * 
     * @type {Dinero}
     * @memberof InvoiceEntry
     */
    priceInclVat: Dinero;
    /**
     * The amount of items in the invoice entry.
     * @type {number}
     * @memberof InvoiceEntry
     */
    amount: number;
    /**
     * The description of the invoice entry item.
     * @type {string}
     * @memberof InvoiceEntry
     */
    description: string;
    /**
     * The percentage of vat applied to this item.
     * @type {number}
     * @memberof InvoiceEntry
     */
    vatPercentage: number;
    /**
     * The creation date of the object.
     * @type {string}
     * @memberof InvoiceEntry
     */
    createdAt?: string;
    /**
     * The last update date of the object.
     * @type {string}
     * @memberof InvoiceEntry
     */
    updatedAt?: string;
    /**
     * The current version of the object.
     * @type {number}
     * @memberof InvoiceEntry
     */
    version?: number;
}

/**
 * Check if a given object implements the InvoiceEntry interface.
 */
export function instanceOfInvoiceEntry(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "invoice" in value;
    isInstance = isInstance && "priceInclVat" in value;
    isInstance = isInstance && "amount" in value;
    isInstance = isInstance && "description" in value;
    isInstance = isInstance && "vatPercentage" in value;

    return isInstance;
}

export function InvoiceEntryFromJSON(json: any): InvoiceEntry {
    return InvoiceEntryFromJSONTyped(json, false);
}

export function InvoiceEntryFromJSONTyped(json: any, ignoreDiscriminator: boolean): InvoiceEntry {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'invoice': InvoiceFromJSON(json['invoice']),
        'priceInclVat': DineroFromJSON(json['priceInclVat']),
        'amount': json['amount'],
        'description': json['description'],
        'vatPercentage': json['vatPercentage'],
        'createdAt': !exists(json, 'createdAt') ? undefined : json['createdAt'],
        'updatedAt': !exists(json, 'updatedAt') ? undefined : json['updatedAt'],
        'version': !exists(json, 'version') ? undefined : json['version'],
    };
}

export function InvoiceEntryToJSON(value?: InvoiceEntry | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'invoice': InvoiceToJSON(value.invoice),
        'priceInclVat': DineroToJSON(value.priceInclVat),
        'amount': value.amount,
        'description': value.description,
        'vatPercentage': value.vatPercentage,
        'createdAt': value.createdAt,
        'updatedAt': value.updatedAt,
        'version': value.version,
    };
}

