/* tslint:disable */
/* eslint-disable */
/**
 * sudosos-back-end
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Invoice } from './Invoice';
import {
    InvoiceFromJSON,
    InvoiceFromJSONTyped,
    InvoiceToJSON,
} from './Invoice';
import type { User } from './User';
import {
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
} from './User';

/**
 * 
 * @export
 * @interface InvoiceStatus
 */
export interface InvoiceStatus {
    /**
     * 
     * @type {Invoice}
     * @memberof InvoiceStatus
     */
    invoice: Invoice;
    /**
     * 
     * @type {User}
     * @memberof InvoiceStatus
     */
    changedBy: User;
    /**
     * The state of the Invoice
     * @type {string}
     * @memberof InvoiceStatus
     */
    state: string;
    /**
     * The creation date of the object.
     * @type {string}
     * @memberof InvoiceStatus
     */
    createdAt?: string;
    /**
     * The last update date of the object.
     * @type {string}
     * @memberof InvoiceStatus
     */
    updatedAt?: string;
    /**
     * The current version of the object.
     * @type {number}
     * @memberof InvoiceStatus
     */
    version?: number;
}

/**
 * Check if a given object implements the InvoiceStatus interface.
 */
export function instanceOfInvoiceStatus(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "invoice" in value;
    isInstance = isInstance && "changedBy" in value;
    isInstance = isInstance && "state" in value;

    return isInstance;
}

export function InvoiceStatusFromJSON(json: any): InvoiceStatus {
    return InvoiceStatusFromJSONTyped(json, false);
}

export function InvoiceStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): InvoiceStatus {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'invoice': InvoiceFromJSON(json['invoice']),
        'changedBy': UserFromJSON(json['changedBy']),
        'state': json['state'],
        'createdAt': !exists(json, 'createdAt') ? undefined : json['createdAt'],
        'updatedAt': !exists(json, 'updatedAt') ? undefined : json['updatedAt'],
        'version': !exists(json, 'version') ? undefined : json['version'],
    };
}

export function InvoiceStatusToJSON(value?: InvoiceStatus | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'invoice': InvoiceToJSON(value.invoice),
        'changedBy': UserToJSON(value.changedBy),
        'state': value.state,
        'createdAt': value.createdAt,
        'updatedAt': value.updatedAt,
        'version': value.version,
    };
}

