/* tslint:disable */
/* eslint-disable */
/**
 * sudosos-back-end
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { DineroObjectRequest } from './DineroObjectRequest';
import {
    DineroObjectRequestFromJSON,
    DineroObjectRequestFromJSONTyped,
    DineroObjectRequestToJSON,
} from './DineroObjectRequest';

/**
 * 
 * @export
 * @interface InvoiceEntryRequest
 */
export interface InvoiceEntryRequest {
    /**
     * The description of the entry
     * @type {string}
     * @memberof InvoiceEntryRequest
     */
    description: string;
    /**
     * Amount of item sold.
     * @type {number}
     * @memberof InvoiceEntryRequest
     */
    amount: number;
    /**
     * 
     * @type {DineroObjectRequest}
     * @memberof InvoiceEntryRequest
     */
    priceInclVat: DineroObjectRequest;
    /**
     * The percentage of VAT applied to this item
     * @type {number}
     * @memberof InvoiceEntryRequest
     */
    vatPercentage: number;
}

/**
 * Check if a given object implements the InvoiceEntryRequest interface.
 */
export function instanceOfInvoiceEntryRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "description" in value;
    isInstance = isInstance && "amount" in value;
    isInstance = isInstance && "priceInclVat" in value;
    isInstance = isInstance && "vatPercentage" in value;

    return isInstance;
}

export function InvoiceEntryRequestFromJSON(json: any): InvoiceEntryRequest {
    return InvoiceEntryRequestFromJSONTyped(json, false);
}

export function InvoiceEntryRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): InvoiceEntryRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'description': json['description'],
        'amount': json['amount'],
        'priceInclVat': DineroObjectRequestFromJSON(json['priceInclVat']),
        'vatPercentage': json['vatPercentage'],
    };
}

export function InvoiceEntryRequestToJSON(value?: InvoiceEntryRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'description': value.description,
        'amount': value.amount,
        'priceInclVat': DineroObjectRequestToJSON(value.priceInclVat),
        'vatPercentage': value.vatPercentage,
    };
}

