/* tslint:disable */
/* eslint-disable */
/**
 * sudosos-back-end
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LocalAuthenticator
 */
export interface LocalAuthenticator {
    /**
     * The Password code of this user (hashed)
     * @type {string}
     * @memberof LocalAuthenticator
     */
    hash: string;
    /**
     * The creation date of the object.
     * @type {string}
     * @memberof LocalAuthenticator
     */
    createdAt?: string;
    /**
     * The last update date of the object.
     * @type {string}
     * @memberof LocalAuthenticator
     */
    updatedAt?: string;
    /**
     * The current version of the object.
     * @type {number}
     * @memberof LocalAuthenticator
     */
    version?: number;
}

/**
 * Check if a given object implements the LocalAuthenticator interface.
 */
export function instanceOfLocalAuthenticator(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "hash" in value;

    return isInstance;
}

export function LocalAuthenticatorFromJSON(json: any): LocalAuthenticator {
    return LocalAuthenticatorFromJSONTyped(json, false);
}

export function LocalAuthenticatorFromJSONTyped(json: any, ignoreDiscriminator: boolean): LocalAuthenticator {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'hash': json['hash'],
        'createdAt': !exists(json, 'createdAt') ? undefined : json['createdAt'],
        'updatedAt': !exists(json, 'updatedAt') ? undefined : json['updatedAt'],
        'version': !exists(json, 'version') ? undefined : json['version'],
    };
}

export function LocalAuthenticatorToJSON(value?: LocalAuthenticator | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'hash': value.hash,
        'createdAt': value.createdAt,
        'updatedAt': value.updatedAt,
        'version': value.version,
    };
}

