/* tslint:disable */
/* eslint-disable */
/**
 * sudosos-back-end
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { User } from './User';
import {
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
} from './User';

/**
 * 
 * @export
 * @interface MemberAuthenticator
 */
export interface MemberAuthenticator {
    /**
     * 
     * @type {User}
     * @memberof MemberAuthenticator
     */
    authenticateAs: User;
    /**
     * The creation date of the object.
     * @type {string}
     * @memberof MemberAuthenticator
     */
    createdAt?: string;
    /**
     * The last update date of the object.
     * @type {string}
     * @memberof MemberAuthenticator
     */
    updatedAt?: string;
    /**
     * The current version of the object.
     * @type {number}
     * @memberof MemberAuthenticator
     */
    version?: number;
}

/**
 * Check if a given object implements the MemberAuthenticator interface.
 */
export function instanceOfMemberAuthenticator(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "authenticateAs" in value;

    return isInstance;
}

export function MemberAuthenticatorFromJSON(json: any): MemberAuthenticator {
    return MemberAuthenticatorFromJSONTyped(json, false);
}

export function MemberAuthenticatorFromJSONTyped(json: any, ignoreDiscriminator: boolean): MemberAuthenticator {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'authenticateAs': UserFromJSON(json['authenticateAs']),
        'createdAt': !exists(json, 'createdAt') ? undefined : json['createdAt'],
        'updatedAt': !exists(json, 'updatedAt') ? undefined : json['updatedAt'],
        'version': !exists(json, 'version') ? undefined : json['version'],
    };
}

export function MemberAuthenticatorToJSON(value?: MemberAuthenticator | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'authenticateAs': UserToJSON(value.authenticateAs),
        'createdAt': value.createdAt,
        'updatedAt': value.updatedAt,
        'version': value.version,
    };
}

