/* tslint:disable */
/* eslint-disable */
/**
 * sudosos-back-end
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { BaseTransactionResponse } from './BaseTransactionResponse';
import {
    BaseTransactionResponseFromJSON,
    BaseTransactionResponseFromJSONTyped,
    BaseTransactionResponseToJSON,
} from './BaseTransactionResponse';
import type { PaginationResult } from './PaginationResult';
import {
    PaginationResultFromJSON,
    PaginationResultFromJSONTyped,
    PaginationResultToJSON,
} from './PaginationResult';

/**
 * 
 * @export
 * @interface PaginatedBaseTransactionResponse
 */
export interface PaginatedBaseTransactionResponse {
    /**
     * 
     * @type {PaginationResult}
     * @memberof PaginatedBaseTransactionResponse
     */
    pagination?: PaginationResult;
    /**
     * 
     * @type {Array<BaseTransactionResponse>}
     * @memberof PaginatedBaseTransactionResponse
     */
    records?: Array<BaseTransactionResponse>;
}

/**
 * Check if a given object implements the PaginatedBaseTransactionResponse interface.
 */
export function instanceOfPaginatedBaseTransactionResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PaginatedBaseTransactionResponseFromJSON(json: any): PaginatedBaseTransactionResponse {
    return PaginatedBaseTransactionResponseFromJSONTyped(json, false);
}

export function PaginatedBaseTransactionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedBaseTransactionResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'pagination': !exists(json, '_pagination') ? undefined : PaginationResultFromJSON(json['_pagination']),
        'records': !exists(json, 'records') ? undefined : ((json['records'] as Array<any>).map(BaseTransactionResponseFromJSON)),
    };
}

export function PaginatedBaseTransactionResponseToJSON(value?: PaginatedBaseTransactionResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        '_pagination': PaginationResultToJSON(value.pagination),
        'records': value.records === undefined ? undefined : ((value.records as Array<any>).map(BaseTransactionResponseToJSON)),
    };
}

