/* tslint:disable */
/* eslint-disable */
/**
 * sudosos-back-end
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { PaginationResult } from './PaginationResult';
import {
    PaginationResultFromJSON,
    PaginationResultFromJSONTyped,
    PaginationResultToJSON,
} from './PaginationResult';
import type { UserResponse } from './UserResponse';
import {
    UserResponseFromJSON,
    UserResponseFromJSONTyped,
    UserResponseToJSON,
} from './UserResponse';

/**
 * 
 * @export
 * @interface PaginatedUserResponse
 */
export interface PaginatedUserResponse {
    /**
     * 
     * @type {PaginationResult}
     * @memberof PaginatedUserResponse
     */
    pagination?: PaginationResult;
    /**
     * 
     * @type {Array<UserResponse>}
     * @memberof PaginatedUserResponse
     */
    records?: Array<UserResponse>;
}

/**
 * Check if a given object implements the PaginatedUserResponse interface.
 */
export function instanceOfPaginatedUserResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PaginatedUserResponseFromJSON(json: any): PaginatedUserResponse {
    return PaginatedUserResponseFromJSONTyped(json, false);
}

export function PaginatedUserResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedUserResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'pagination': !exists(json, '_pagination') ? undefined : PaginationResultFromJSON(json['_pagination']),
        'records': !exists(json, 'records') ? undefined : ((json['records'] as Array<any>).map(UserResponseFromJSON)),
    };
}

export function PaginatedUserResponseToJSON(value?: PaginatedUserResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        '_pagination': PaginationResultToJSON(value.pagination),
        'records': value.records === undefined ? undefined : ((value.records as Array<any>).map(UserResponseToJSON)),
    };
}

