/* tslint:disable */
/* eslint-disable */
/**
 * sudosos-back-end
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { BannerResponse } from './BannerResponse';
import {
    BannerResponseFromJSON,
    BannerResponseFromJSONTyped,
    BannerResponseToJSON,
} from './BannerResponse';
import type { PaginationResult } from './PaginationResult';
import {
    PaginationResultFromJSON,
    PaginationResultFromJSONTyped,
    PaginationResultToJSON,
} from './PaginationResult';

/**
 * 
 * @export
 * @interface PaginatedBannerResponse
 */
export interface PaginatedBannerResponse {
    /**
     * 
     * @type {PaginationResult}
     * @memberof PaginatedBannerResponse
     */
    pagination?: PaginationResult;
    /**
     * 
     * @type {Array<BannerResponse>}
     * @memberof PaginatedBannerResponse
     */
    records?: Array<BannerResponse>;
}

/**
 * Check if a given object implements the PaginatedBannerResponse interface.
 */
export function instanceOfPaginatedBannerResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PaginatedBannerResponseFromJSON(json: any): PaginatedBannerResponse {
    return PaginatedBannerResponseFromJSONTyped(json, false);
}

export function PaginatedBannerResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedBannerResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'pagination': !exists(json, '_pagination') ? undefined : PaginationResultFromJSON(json['_pagination']),
        'records': !exists(json, 'records') ? undefined : ((json['records'] as Array<any>).map(BannerResponseFromJSON)),
    };
}

export function PaginatedBannerResponseToJSON(value?: PaginatedBannerResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        '_pagination': PaginationResultToJSON(value.pagination),
        'records': value.records === undefined ? undefined : ((value.records as Array<any>).map(BannerResponseToJSON)),
    };
}

