/* tslint:disable */
/* eslint-disable */
/**
 * sudosos-back-end
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PaginationResult
 */
export interface PaginationResult {
    /**
     * Number of records queried
     * @type {number}
     * @memberof PaginationResult
     */
    take?: number;
    /**
     * Number of skipped records
     * @type {number}
     * @memberof PaginationResult
     */
    skip?: number;
    /**
     * Total number of resulting records
     * @type {number}
     * @memberof PaginationResult
     */
    count?: number;
}

/**
 * Check if a given object implements the PaginationResult interface.
 */
export function instanceOfPaginationResult(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PaginationResultFromJSON(json: any): PaginationResult {
    return PaginationResultFromJSONTyped(json, false);
}

export function PaginationResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginationResult {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'take': !exists(json, 'take') ? undefined : json['take'],
        'skip': !exists(json, 'skip') ? undefined : json['skip'],
        'count': !exists(json, 'count') ? undefined : json['count'],
    };
}

export function PaginationResultToJSON(value?: PaginationResult | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'take': value.take,
        'skip': value.skip,
        'count': value.count,
    };
}

