/* tslint:disable */
/* eslint-disable */
/**
 * sudosos-back-end
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { BasePayoutRequestResponse } from './BasePayoutRequestResponse';
import {
    BasePayoutRequestResponseFromJSON,
    BasePayoutRequestResponseFromJSONTyped,
    BasePayoutRequestResponseToJSON,
} from './BasePayoutRequestResponse';
import type { PaginationResult } from './PaginationResult';
import {
    PaginationResultFromJSON,
    PaginationResultFromJSONTyped,
    PaginationResultToJSON,
} from './PaginationResult';

/**
 * 
 * @export
 * @interface PaginatedBasePayoutRequestResponse
 */
export interface PaginatedBasePayoutRequestResponse {
    /**
     * 
     * @type {PaginationResult}
     * @memberof PaginatedBasePayoutRequestResponse
     */
    pagination?: PaginationResult;
    /**
     * 
     * @type {Array<BasePayoutRequestResponse>}
     * @memberof PaginatedBasePayoutRequestResponse
     */
    records?: Array<BasePayoutRequestResponse>;
}

/**
 * Check if a given object implements the PaginatedBasePayoutRequestResponse interface.
 */
export function instanceOfPaginatedBasePayoutRequestResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PaginatedBasePayoutRequestResponseFromJSON(json: any): PaginatedBasePayoutRequestResponse {
    return PaginatedBasePayoutRequestResponseFromJSONTyped(json, false);
}

export function PaginatedBasePayoutRequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedBasePayoutRequestResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'pagination': !exists(json, '_pagination') ? undefined : PaginationResultFromJSON(json['_pagination']),
        'records': !exists(json, 'records') ? undefined : ((json['records'] as Array<any>).map(BasePayoutRequestResponseFromJSON)),
    };
}

export function PaginatedBasePayoutRequestResponseToJSON(value?: PaginatedBasePayoutRequestResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        '_pagination': PaginationResultToJSON(value.pagination),
        'records': value.records === undefined ? undefined : ((value.records as Array<any>).map(BasePayoutRequestResponseToJSON)),
    };
}

