/* tslint:disable */
/* eslint-disable */
/**
 * sudosos-back-end
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { PaginationResult } from './PaginationResult';
import {
    PaginationResultFromJSON,
    PaginationResultFromJSONTyped,
    PaginationResultToJSON,
} from './PaginationResult';
import type { TransferResponse } from './TransferResponse';
import {
    TransferResponseFromJSON,
    TransferResponseFromJSONTyped,
    TransferResponseToJSON,
} from './TransferResponse';

/**
 * 
 * @export
 * @interface PaginatedTransferResponse
 */
export interface PaginatedTransferResponse {
    /**
     * 
     * @type {PaginationResult}
     * @memberof PaginatedTransferResponse
     */
    pagination?: PaginationResult;
    /**
     * 
     * @type {Array<TransferResponse>}
     * @memberof PaginatedTransferResponse
     */
    records?: Array<TransferResponse>;
}

/**
 * Check if a given object implements the PaginatedTransferResponse interface.
 */
export function instanceOfPaginatedTransferResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PaginatedTransferResponseFromJSON(json: any): PaginatedTransferResponse {
    return PaginatedTransferResponseFromJSONTyped(json, false);
}

export function PaginatedTransferResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedTransferResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'pagination': !exists(json, '_pagination') ? undefined : PaginationResultFromJSON(json['_pagination']),
        'records': !exists(json, 'records') ? undefined : ((json['records'] as Array<any>).map(TransferResponseFromJSON)),
    };
}

export function PaginatedTransferResponseToJSON(value?: PaginatedTransferResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        '_pagination': PaginationResultToJSON(value.pagination),
        'records': value.records === undefined ? undefined : ((value.records as Array<any>).map(TransferResponseToJSON)),
    };
}

