/* tslint:disable */
/* eslint-disable */
/**
 * sudosos-back-end
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ContainerWithProductsResponse } from './ContainerWithProductsResponse';
import {
    ContainerWithProductsResponseFromJSON,
    ContainerWithProductsResponseFromJSONTyped,
    ContainerWithProductsResponseToJSON,
} from './ContainerWithProductsResponse';
import type { PaginationResult } from './PaginationResult';
import {
    PaginationResultFromJSON,
    PaginationResultFromJSONTyped,
    PaginationResultToJSON,
} from './PaginationResult';

/**
 * 
 * @export
 * @interface PaginatedContainerWithProductResponse
 */
export interface PaginatedContainerWithProductResponse {
    /**
     * 
     * @type {PaginationResult}
     * @memberof PaginatedContainerWithProductResponse
     */
    pagination?: PaginationResult;
    /**
     * 
     * @type {Array<ContainerWithProductsResponse>}
     * @memberof PaginatedContainerWithProductResponse
     */
    records?: Array<ContainerWithProductsResponse>;
}

/**
 * Check if a given object implements the PaginatedContainerWithProductResponse interface.
 */
export function instanceOfPaginatedContainerWithProductResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PaginatedContainerWithProductResponseFromJSON(json: any): PaginatedContainerWithProductResponse {
    return PaginatedContainerWithProductResponseFromJSONTyped(json, false);
}

export function PaginatedContainerWithProductResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedContainerWithProductResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'pagination': !exists(json, '_pagination') ? undefined : PaginationResultFromJSON(json['_pagination']),
        'records': !exists(json, 'records') ? undefined : ((json['records'] as Array<any>).map(ContainerWithProductsResponseFromJSON)),
    };
}

export function PaginatedContainerWithProductResponseToJSON(value?: PaginatedContainerWithProductResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        '_pagination': PaginationResultToJSON(value.pagination),
        'records': value.records === undefined ? undefined : ((value.records as Array<any>).map(ContainerWithProductsResponseToJSON)),
    };
}

