/* tslint:disable */
/* eslint-disable */
/**
 * sudosos-back-end
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { PaginationResult } from './PaginationResult';
import {
    PaginationResultFromJSON,
    PaginationResultFromJSONTyped,
    PaginationResultToJSON,
} from './PaginationResult';

/**
 * 
 * @export
 * @interface PaginatedUpdatedPointOfSaleResponse
 */
export interface PaginatedUpdatedPointOfSaleResponse {
    /**
     * 
     * @type {PaginationResult}
     * @memberof PaginatedUpdatedPointOfSaleResponse
     */
    pagination?: PaginationResult;
    /**
     * 
     * @type {Array<object>}
     * @memberof PaginatedUpdatedPointOfSaleResponse
     */
    records?: Array<object>;
}

/**
 * Check if a given object implements the PaginatedUpdatedPointOfSaleResponse interface.
 */
export function instanceOfPaginatedUpdatedPointOfSaleResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PaginatedUpdatedPointOfSaleResponseFromJSON(json: any): PaginatedUpdatedPointOfSaleResponse {
    return PaginatedUpdatedPointOfSaleResponseFromJSONTyped(json, false);
}

export function PaginatedUpdatedPointOfSaleResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedUpdatedPointOfSaleResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'pagination': !exists(json, '_pagination') ? undefined : PaginationResultFromJSON(json['_pagination']),
        'records': !exists(json, 'records') ? undefined : json['records'],
    };
}

export function PaginatedUpdatedPointOfSaleResponseToJSON(value?: PaginatedUpdatedPointOfSaleResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        '_pagination': PaginationResultToJSON(value.pagination),
        'records': value.records,
    };
}

