/* tslint:disable */
/* eslint-disable */
/**
 * sudosos-back-end
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { PaginationResult } from './PaginationResult';
import {
    PaginationResultFromJSON,
    PaginationResultFromJSONTyped,
    PaginationResultToJSON,
} from './PaginationResult';
import type { VatGroup } from './VatGroup';
import {
    VatGroupFromJSON,
    VatGroupFromJSONTyped,
    VatGroupToJSON,
} from './VatGroup';

/**
 * 
 * @export
 * @interface PaginatedVatGroupResponse
 */
export interface PaginatedVatGroupResponse {
    /**
     * 
     * @type {PaginationResult}
     * @memberof PaginatedVatGroupResponse
     */
    pagination: PaginationResult;
    /**
     * 
     * @type {Array<VatGroup>}
     * @memberof PaginatedVatGroupResponse
     */
    records: Array<VatGroup>;
}

/**
 * Check if a given object implements the PaginatedVatGroupResponse interface.
 */
export function instanceOfPaginatedVatGroupResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "pagination" in value;
    isInstance = isInstance && "records" in value;

    return isInstance;
}

export function PaginatedVatGroupResponseFromJSON(json: any): PaginatedVatGroupResponse {
    return PaginatedVatGroupResponseFromJSONTyped(json, false);
}

export function PaginatedVatGroupResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedVatGroupResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'pagination': PaginationResultFromJSON(json['_pagination']),
        'records': ((json['records'] as Array<any>).map(VatGroupFromJSON)),
    };
}

export function PaginatedVatGroupResponseToJSON(value?: PaginatedVatGroupResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        '_pagination': PaginationResultToJSON(value.pagination),
        'records': ((value.records as Array<any>).map(VatGroupToJSON)),
    };
}

