/* tslint:disable */
/* eslint-disable */
/**
 * sudosos-back-end
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { BalanceResponse } from './BalanceResponse';
import {
    BalanceResponseFromJSON,
    BalanceResponseFromJSONTyped,
    BalanceResponseToJSON,
} from './BalanceResponse';
import type { PaginationResult } from './PaginationResult';
import {
    PaginationResultFromJSON,
    PaginationResultFromJSONTyped,
    PaginationResultToJSON,
} from './PaginationResult';

/**
 * 
 * @export
 * @interface PaginatedBalanceResponse
 */
export interface PaginatedBalanceResponse {
    /**
     * 
     * @type {PaginationResult}
     * @memberof PaginatedBalanceResponse
     */
    pagination?: PaginationResult;
    /**
     * 
     * @type {Array<BalanceResponse>}
     * @memberof PaginatedBalanceResponse
     */
    records?: Array<BalanceResponse>;
}

/**
 * Check if a given object implements the PaginatedBalanceResponse interface.
 */
export function instanceOfPaginatedBalanceResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PaginatedBalanceResponseFromJSON(json: any): PaginatedBalanceResponse {
    return PaginatedBalanceResponseFromJSONTyped(json, false);
}

export function PaginatedBalanceResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedBalanceResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'pagination': !exists(json, '_pagination') ? undefined : PaginationResultFromJSON(json['_pagination']),
        'records': !exists(json, 'records') ? undefined : ((json['records'] as Array<any>).map(BalanceResponseFromJSON)),
    };
}

export function PaginatedBalanceResponseToJSON(value?: PaginatedBalanceResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        '_pagination': PaginationResultToJSON(value.pagination),
        'records': value.records === undefined ? undefined : ((value.records as Array<any>).map(BalanceResponseToJSON)),
    };
}

