/* tslint:disable */
/* eslint-disable */
/**
 * sudosos-back-end
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { User } from './User';
import {
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
} from './User';

/**
 * 
 * @export
 * @interface PointOfSale
 */
export interface PointOfSale {
    /**
     * The current revision of the pointOfSale.
     * Can be null if no revision exists.
     * @type {number}
     * @memberof PointOfSale
     */
    currentRevision?: number;
    /**
     * 
     * @type {User}
     * @memberof PointOfSale
     */
    owner: User;
    /**
     * The creation date of the object.
     * @type {string}
     * @memberof PointOfSale
     */
    createdAt?: string;
    /**
     * The last update date of the object.
     * @type {string}
     * @memberof PointOfSale
     */
    updatedAt?: string;
    /**
     * The current version of the object.
     * @type {number}
     * @memberof PointOfSale
     */
    version?: number;
}

/**
 * Check if a given object implements the PointOfSale interface.
 */
export function instanceOfPointOfSale(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "owner" in value;

    return isInstance;
}

export function PointOfSaleFromJSON(json: any): PointOfSale {
    return PointOfSaleFromJSONTyped(json, false);
}

export function PointOfSaleFromJSONTyped(json: any, ignoreDiscriminator: boolean): PointOfSale {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'currentRevision': !exists(json, 'currentRevision') ? undefined : json['currentRevision'],
        'owner': UserFromJSON(json['owner']),
        'createdAt': !exists(json, 'createdAt') ? undefined : json['createdAt'],
        'updatedAt': !exists(json, 'updatedAt') ? undefined : json['updatedAt'],
        'version': !exists(json, 'version') ? undefined : json['version'],
    };
}

export function PointOfSaleToJSON(value?: PointOfSale | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'currentRevision': value.currentRevision,
        'owner': UserToJSON(value.owner),
        'createdAt': value.createdAt,
        'updatedAt': value.updatedAt,
        'version': value.version,
    };
}

