/* tslint:disable */
/* eslint-disable */
/**
 * sudosos-back-end
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { PointOfSale } from './PointOfSale';
import {
    PointOfSaleFromJSON,
    PointOfSaleFromJSONTyped,
    PointOfSaleToJSON,
} from './PointOfSale';
import type { Product } from './Product';
import {
    ProductFromJSON,
    ProductFromJSONTyped,
    ProductToJSON,
} from './Product';

/**
 * 
 * @export
 * @interface ProductOrdering
 */
export interface ProductOrdering {
    /**
     * 
     * @type {PointOfSale}
     * @memberof ProductOrdering
     */
    pos: PointOfSale;
    /**
     * 
     * @type {Product}
     * @memberof ProductOrdering
     */
    product: Product;
    /**
     * The order number of the product in the pointOfSale.
     * @type {number}
     * @memberof ProductOrdering
     */
    order: number;
}

/**
 * Check if a given object implements the ProductOrdering interface.
 */
export function instanceOfProductOrdering(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "pos" in value;
    isInstance = isInstance && "product" in value;
    isInstance = isInstance && "order" in value;

    return isInstance;
}

export function ProductOrderingFromJSON(json: any): ProductOrdering {
    return ProductOrderingFromJSONTyped(json, false);
}

export function ProductOrderingFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductOrdering {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'pos': PointOfSaleFromJSON(json['pos']),
        'product': ProductFromJSON(json['product']),
        'order': json['order'],
    };
}

export function ProductOrderingToJSON(value?: ProductOrdering | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'pos': PointOfSaleToJSON(value.pos),
        'product': ProductToJSON(value.product),
        'order': value.order,
    };
}

