/* tslint:disable */
/* eslint-disable */
/**
 * sudosos-back-end
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ProductImage } from './ProductImage';
import {
    ProductImageFromJSON,
    ProductImageFromJSONTyped,
    ProductImageToJSON,
} from './ProductImage';
import type { User } from './User';
import {
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
} from './User';

/**
 * 
 * @export
 * @interface Product
 */
export interface Product {
    /**
     * The current revision of the product.
     * Can be null if no revision exists.
     * @type {number}
     * @memberof Product
     */
    currentRevision?: number;
    /**
     * 
     * @type {User}
     * @memberof Product
     */
    owner: User;
    /**
     * 
     * @type {ProductImage}
     * @memberof Product
     */
    image?: ProductImage;
    /**
     * The creation date of the object.
     * @type {string}
     * @memberof Product
     */
    createdAt?: string;
    /**
     * The last update date of the object.
     * @type {string}
     * @memberof Product
     */
    updatedAt?: string;
    /**
     * The current version of the object.
     * @type {number}
     * @memberof Product
     */
    version?: number;
}

/**
 * Check if a given object implements the Product interface.
 */
export function instanceOfProduct(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "owner" in value;

    return isInstance;
}

export function ProductFromJSON(json: any): Product {
    return ProductFromJSONTyped(json, false);
}

export function ProductFromJSONTyped(json: any, ignoreDiscriminator: boolean): Product {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'currentRevision': !exists(json, 'currentRevision') ? undefined : json['currentRevision'],
        'owner': UserFromJSON(json['owner']),
        'image': !exists(json, 'image') ? undefined : ProductImageFromJSON(json['image']),
        'createdAt': !exists(json, 'createdAt') ? undefined : json['createdAt'],
        'updatedAt': !exists(json, 'updatedAt') ? undefined : json['updatedAt'],
        'version': !exists(json, 'version') ? undefined : json['version'],
    };
}

export function ProductToJSON(value?: Product | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'currentRevision': value.currentRevision,
        'owner': UserToJSON(value.owner),
        'image': ProductImageToJSON(value.image),
        'createdAt': value.createdAt,
        'updatedAt': value.updatedAt,
        'version': value.version,
    };
}

