/* tslint:disable */
/* eslint-disable */
/**
 * sudosos-back-end
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RelationResponse
 */
export interface RelationResponse {
    /**
     * The the ownership relation towards the entity.
     * @type {string}
     * @memberof RelationResponse
     */
    relation?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof RelationResponse
     */
    attributes?: Array<string>;
}

/**
 * Check if a given object implements the RelationResponse interface.
 */
export function instanceOfRelationResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function RelationResponseFromJSON(json: any): RelationResponse {
    return RelationResponseFromJSONTyped(json, false);
}

export function RelationResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RelationResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'relation': !exists(json, 'relation') ? undefined : json['relation'],
        'attributes': !exists(json, 'attributes') ? undefined : json['attributes'],
    };
}

export function RelationResponseToJSON(value?: RelationResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'relation': value.relation,
        'attributes': value.attributes,
    };
}

