/* tslint:disable */
/* eslint-disable */
/**
 * sudosos-back-end
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResetToken
 */
export interface ResetToken {
    /**
     * The end date from which the token is expired
     * @type {string}
     * @memberof ResetToken
     */
    expires: string;
    /**
     * The creation date of the object.
     * @type {string}
     * @memberof ResetToken
     */
    createdAt?: string;
    /**
     * The last update date of the object.
     * @type {string}
     * @memberof ResetToken
     */
    updatedAt?: string;
    /**
     * The current version of the object.
     * @type {number}
     * @memberof ResetToken
     */
    version?: number;
}

/**
 * Check if a given object implements the ResetToken interface.
 */
export function instanceOfResetToken(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "expires" in value;

    return isInstance;
}

export function ResetTokenFromJSON(json: any): ResetToken {
    return ResetTokenFromJSONTyped(json, false);
}

export function ResetTokenFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResetToken {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'expires': json['expires'],
        'createdAt': !exists(json, 'createdAt') ? undefined : json['createdAt'],
        'updatedAt': !exists(json, 'updatedAt') ? undefined : json['updatedAt'],
        'version': !exists(json, 'version') ? undefined : json['version'],
    };
}

export function ResetTokenToJSON(value?: ResetToken | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'expires': value.expires,
        'createdAt': value.createdAt,
        'updatedAt': value.updatedAt,
        'version': value.version,
    };
}

