/* tslint:disable */
/* eslint-disable */
/**
 * sudosos-back-end
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResetLocalRequest
 */
export interface ResetLocalRequest {
    /**
     * The mail of the user
     * @type {string}
     * @memberof ResetLocalRequest
     */
    accountMail: string;
}

/**
 * Check if a given object implements the ResetLocalRequest interface.
 */
export function instanceOfResetLocalRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "accountMail" in value;

    return isInstance;
}

export function ResetLocalRequestFromJSON(json: any): ResetLocalRequest {
    return ResetLocalRequestFromJSONTyped(json, false);
}

export function ResetLocalRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResetLocalRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'accountMail': json['accountMail'],
    };
}

export function ResetLocalRequestToJSON(value?: ResetLocalRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'accountMail': value.accountMail,
    };
}

