/* tslint:disable */
/* eslint-disable */
/**
 * sudosos-back-end
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RevisionRequest
 */
export interface RevisionRequest {
    /**
     * revision id
     * @type {number}
     * @memberof RevisionRequest
     */
    id?: number;
    /**
     * revision number
     * @type {number}
     * @memberof RevisionRequest
     */
    revision?: number;
}

/**
 * Check if a given object implements the RevisionRequest interface.
 */
export function instanceOfRevisionRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function RevisionRequestFromJSON(json: any): RevisionRequest {
    return RevisionRequestFromJSONTyped(json, false);
}

export function RevisionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RevisionRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'revision': !exists(json, 'revision') ? undefined : json['revision'],
    };
}

export function RevisionRequestToJSON(value?: RevisionRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'revision': value.revision,
    };
}

