/* tslint:disable */
/* eslint-disable */
/**
 * sudosos-back-end
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { EntityResponse } from './EntityResponse';
import {
    EntityResponseFromJSON,
    EntityResponseFromJSONTyped,
    EntityResponseToJSON,
} from './EntityResponse';

/**
 * 
 * @export
 * @interface RoleResponse
 */
export interface RoleResponse {
    /**
     * The name of the role.
     * @type {string}
     * @memberof RoleResponse
     */
    role: string;
    /**
     * 
     * @type {Array<EntityResponse>}
     * @memberof RoleResponse
     */
    entities?: Array<EntityResponse>;
}

/**
 * Check if a given object implements the RoleResponse interface.
 */
export function instanceOfRoleResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "role" in value;

    return isInstance;
}

export function RoleResponseFromJSON(json: any): RoleResponse {
    return RoleResponseFromJSONTyped(json, false);
}

export function RoleResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RoleResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'role': json['role'],
        'entities': !exists(json, 'entities') ? undefined : ((json['entities'] as Array<any>).map(EntityResponseFromJSON)),
    };
}

export function RoleResponseToJSON(value?: RoleResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'role': value.role,
        'entities': value.entities === undefined ? undefined : ((value.entities as Array<any>).map(EntityResponseToJSON)),
    };
}

