/* tslint:disable */
/* eslint-disable */
/**
 * sudosos-back-end
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { UserResponse } from './UserResponse';
import {
    UserResponseFromJSON,
    UserResponseFromJSONTyped,
    UserResponseToJSON,
} from './UserResponse';

/**
 * 
 * @export
 * @interface SimpleFileResponse
 */
export interface SimpleFileResponse {
    /**
     * The filename of the file
     * @type {string}
     * @memberof SimpleFileResponse
     */
    downloadName: string;
    /**
     * The location of the file in storage
     * @type {string}
     * @memberof SimpleFileResponse
     */
    location: string;
    /**
     * 
     * @type {UserResponse}
     * @memberof SimpleFileResponse
     */
    createdBy: UserResponse;
    /**
     * The unique id of the entity.
     * @type {number}
     * @memberof SimpleFileResponse
     */
    id: number;
    /**
     * The creation Date of the entity.
     * @type {string}
     * @memberof SimpleFileResponse
     */
    createdAt?: string;
    /**
     * The last update Date of the entity.
     * @type {string}
     * @memberof SimpleFileResponse
     */
    updatedAt?: string;
    /**
     * The version of the entity.
     * @type {number}
     * @memberof SimpleFileResponse
     */
    version?: number;
}

/**
 * Check if a given object implements the SimpleFileResponse interface.
 */
export function instanceOfSimpleFileResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "downloadName" in value;
    isInstance = isInstance && "location" in value;
    isInstance = isInstance && "createdBy" in value;
    isInstance = isInstance && "id" in value;

    return isInstance;
}

export function SimpleFileResponseFromJSON(json: any): SimpleFileResponse {
    return SimpleFileResponseFromJSONTyped(json, false);
}

export function SimpleFileResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SimpleFileResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'downloadName': json['downloadName'],
        'location': json['location'],
        'createdBy': UserResponseFromJSON(json['createdBy']),
        'id': json['id'],
        'createdAt': !exists(json, 'createdAt') ? undefined : json['createdAt'],
        'updatedAt': !exists(json, 'updatedAt') ? undefined : json['updatedAt'],
        'version': !exists(json, 'version') ? undefined : json['version'],
    };
}

export function SimpleFileResponseToJSON(value?: SimpleFileResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'downloadName': value.downloadName,
        'location': value.location,
        'createdBy': UserResponseToJSON(value.createdBy),
        'id': value.id,
        'createdAt': value.createdAt,
        'updatedAt': value.updatedAt,
        'version': value.version,
    };
}

