/* tslint:disable */
/* eslint-disable */
/**
 * sudosos-back-end
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StripePaymentIntentResponse
 */
export interface StripePaymentIntentResponse {
    /**
     * ID of the intent in Stripe.
     * @type {string}
     * @memberof StripePaymentIntentResponse
     */
    stripeId: string;
    /**
     * The client secret of the created Payment Intent.
     * @type {string}
     * @memberof StripePaymentIntentResponse
     */
    clientSecret: string;
    /**
     * The unique id of the entity.
     * @type {number}
     * @memberof StripePaymentIntentResponse
     */
    id: number;
    /**
     * The creation Date of the entity.
     * @type {string}
     * @memberof StripePaymentIntentResponse
     */
    createdAt?: string;
    /**
     * The last update Date of the entity.
     * @type {string}
     * @memberof StripePaymentIntentResponse
     */
    updatedAt?: string;
    /**
     * The version of the entity.
     * @type {number}
     * @memberof StripePaymentIntentResponse
     */
    version?: number;
}

/**
 * Check if a given object implements the StripePaymentIntentResponse interface.
 */
export function instanceOfStripePaymentIntentResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "stripeId" in value;
    isInstance = isInstance && "clientSecret" in value;
    isInstance = isInstance && "id" in value;

    return isInstance;
}

export function StripePaymentIntentResponseFromJSON(json: any): StripePaymentIntentResponse {
    return StripePaymentIntentResponseFromJSONTyped(json, false);
}

export function StripePaymentIntentResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): StripePaymentIntentResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'stripeId': json['stripeId'],
        'clientSecret': json['clientSecret'],
        'id': json['id'],
        'createdAt': !exists(json, 'createdAt') ? undefined : json['createdAt'],
        'updatedAt': !exists(json, 'updatedAt') ? undefined : json['updatedAt'],
        'version': !exists(json, 'version') ? undefined : json['version'],
    };
}

export function StripePaymentIntentResponseToJSON(value?: StripePaymentIntentResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'stripeId': value.stripeId,
        'clientSecret': value.clientSecret,
        'id': value.id,
        'createdAt': value.createdAt,
        'updatedAt': value.updatedAt,
        'version': value.version,
    };
}

