/* tslint:disable */
/* eslint-disable */
/**
 * sudosos-back-end
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StripeDepositStatusResponse
 */
export interface StripeDepositStatusResponse {
    /**
     * 
     * @type {string}
     * @memberof StripeDepositStatusResponse
     */
    depositStatus: string;
    /**
     * The unique id of the entity.
     * @type {number}
     * @memberof StripeDepositStatusResponse
     */
    id: number;
    /**
     * The creation Date of the entity.
     * @type {string}
     * @memberof StripeDepositStatusResponse
     */
    createdAt?: string;
    /**
     * The last update Date of the entity.
     * @type {string}
     * @memberof StripeDepositStatusResponse
     */
    updatedAt?: string;
    /**
     * The version of the entity.
     * @type {number}
     * @memberof StripeDepositStatusResponse
     */
    version?: number;
}

/**
 * Check if a given object implements the StripeDepositStatusResponse interface.
 */
export function instanceOfStripeDepositStatusResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "depositStatus" in value;
    isInstance = isInstance && "id" in value;

    return isInstance;
}

export function StripeDepositStatusResponseFromJSON(json: any): StripeDepositStatusResponse {
    return StripeDepositStatusResponseFromJSONTyped(json, false);
}

export function StripeDepositStatusResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): StripeDepositStatusResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'depositStatus': json['depositStatus'],
        'id': json['id'],
        'createdAt': !exists(json, 'createdAt') ? undefined : json['createdAt'],
        'updatedAt': !exists(json, 'updatedAt') ? undefined : json['updatedAt'],
        'version': !exists(json, 'version') ? undefined : json['version'],
    };
}

export function StripeDepositStatusResponseToJSON(value?: StripeDepositStatusResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'depositStatus': value.depositStatus,
        'id': value.id,
        'createdAt': value.createdAt,
        'updatedAt': value.updatedAt,
        'version': value.version,
    };
}

