/* tslint:disable */
/* eslint-disable */
/**
 * sudosos-back-end
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { BaseUserResponse } from './BaseUserResponse';
import {
    BaseUserResponseFromJSON,
    BaseUserResponseFromJSONTyped,
    BaseUserResponseToJSON,
} from './BaseUserResponse';
import type { DineroObjectResponse } from './DineroObjectResponse';
import {
    DineroObjectResponseFromJSON,
    DineroObjectResponseFromJSONTyped,
    DineroObjectResponseToJSON,
} from './DineroObjectResponse';
import type { StripeDepositStatusResponse } from './StripeDepositStatusResponse';
import {
    StripeDepositStatusResponseFromJSON,
    StripeDepositStatusResponseFromJSONTyped,
    StripeDepositStatusResponseToJSON,
} from './StripeDepositStatusResponse';

/**
 * 
 * @export
 * @interface StripeDepositResponse
 */
export interface StripeDepositResponse {
    /**
     * The ID of the payment intent in Stripe
     * @type {string}
     * @memberof StripeDepositResponse
     */
    stripeId: string;
    /**
     * 
     * @type {Array<StripeDepositStatusResponse>}
     * @memberof StripeDepositResponse
     */
    depositStatus: Array<StripeDepositStatusResponse>;
    /**
     * 
     * @type {DineroObjectResponse}
     * @memberof StripeDepositResponse
     */
    amount: DineroObjectResponse;
    /**
     * 
     * @type {BaseUserResponse}
     * @memberof StripeDepositResponse
     */
    to: BaseUserResponse;
    /**
     * The unique id of the entity.
     * @type {number}
     * @memberof StripeDepositResponse
     */
    id: number;
    /**
     * The creation Date of the entity.
     * @type {string}
     * @memberof StripeDepositResponse
     */
    createdAt?: string;
    /**
     * The last update Date of the entity.
     * @type {string}
     * @memberof StripeDepositResponse
     */
    updatedAt?: string;
    /**
     * The version of the entity.
     * @type {number}
     * @memberof StripeDepositResponse
     */
    version?: number;
}

/**
 * Check if a given object implements the StripeDepositResponse interface.
 */
export function instanceOfStripeDepositResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "stripeId" in value;
    isInstance = isInstance && "depositStatus" in value;
    isInstance = isInstance && "amount" in value;
    isInstance = isInstance && "to" in value;
    isInstance = isInstance && "id" in value;

    return isInstance;
}

export function StripeDepositResponseFromJSON(json: any): StripeDepositResponse {
    return StripeDepositResponseFromJSONTyped(json, false);
}

export function StripeDepositResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): StripeDepositResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'stripeId': json['stripeId'],
        'depositStatus': ((json['depositStatus'] as Array<any>).map(StripeDepositStatusResponseFromJSON)),
        'amount': DineroObjectResponseFromJSON(json['amount']),
        'to': BaseUserResponseFromJSON(json['to']),
        'id': json['id'],
        'createdAt': !exists(json, 'createdAt') ? undefined : json['createdAt'],
        'updatedAt': !exists(json, 'updatedAt') ? undefined : json['updatedAt'],
        'version': !exists(json, 'version') ? undefined : json['version'],
    };
}

export function StripeDepositResponseToJSON(value?: StripeDepositResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'stripeId': value.stripeId,
        'depositStatus': ((value.depositStatus as Array<any>).map(StripeDepositStatusResponseToJSON)),
        'amount': DineroObjectResponseToJSON(value.amount),
        'to': BaseUserResponseToJSON(value.to),
        'id': value.id,
        'createdAt': value.createdAt,
        'updatedAt': value.updatedAt,
        'version': value.version,
    };
}

