/* tslint:disable */
/* eslint-disable */
/**
 * sudosos-back-end
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { DineroObjectRequest } from './DineroObjectRequest';
import {
    DineroObjectRequestFromJSON,
    DineroObjectRequestFromJSONTyped,
    DineroObjectRequestToJSON,
} from './DineroObjectRequest';
import type { RevisionRequest } from './RevisionRequest';
import {
    RevisionRequestFromJSON,
    RevisionRequestFromJSONTyped,
    RevisionRequestToJSON,
} from './RevisionRequest';

/**
 * 
 * @export
 * @interface SubTransactionRowRequest
 */
export interface SubTransactionRowRequest {
    /**
     * 
     * @type {RevisionRequest}
     * @memberof SubTransactionRowRequest
     */
    product?: RevisionRequest;
    /**
     * amount of this product in subtransaction
     * @type {number}
     * @memberof SubTransactionRowRequest
     */
    amount?: number;
    /**
     * 
     * @type {DineroObjectRequest}
     * @memberof SubTransactionRowRequest
     */
    totalPriceInclVat: DineroObjectRequest;
}

/**
 * Check if a given object implements the SubTransactionRowRequest interface.
 */
export function instanceOfSubTransactionRowRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "totalPriceInclVat" in value;

    return isInstance;
}

export function SubTransactionRowRequestFromJSON(json: any): SubTransactionRowRequest {
    return SubTransactionRowRequestFromJSONTyped(json, false);
}

export function SubTransactionRowRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubTransactionRowRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'product': !exists(json, 'product') ? undefined : RevisionRequestFromJSON(json['product']),
        'amount': !exists(json, 'amount') ? undefined : json['amount'],
        'totalPriceInclVat': DineroObjectRequestFromJSON(json['totalPriceInclVat']),
    };
}

export function SubTransactionRowRequestToJSON(value?: SubTransactionRowRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'product': RevisionRequestToJSON(value.product),
        'amount': value.amount,
        'totalPriceInclVat': DineroObjectRequestToJSON(value.totalPriceInclVat),
    };
}

