/* tslint:disable */
/* eslint-disable */
/**
 * sudosos-back-end
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { PointOfSaleRevision } from './PointOfSaleRevision';
import {
    PointOfSaleRevisionFromJSON,
    PointOfSaleRevisionFromJSONTyped,
    PointOfSaleRevisionToJSON,
} from './PointOfSaleRevision';
import type { SubTransaction } from './SubTransaction';
import {
    SubTransactionFromJSON,
    SubTransactionFromJSONTyped,
    SubTransactionToJSON,
} from './SubTransaction';
import type { User } from './User';
import {
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
} from './User';

/**
 * 
 * @export
 * @interface Transaction
 */
export interface Transaction {
    /**
     * 
     * @type {User}
     * @memberof Transaction
     */
    from: User;
    /**
     * 
     * @type {User}
     * @memberof Transaction
     */
    createdBy: User;
    /**
     * 
     * @type {Array<SubTransaction>}
     * @memberof Transaction
     */
    subTransactions: Array<SubTransaction>;
    /**
     * 
     * @type {PointOfSaleRevision}
     * @memberof Transaction
     */
    pointOfSale: PointOfSaleRevision;
    /**
     * The creation date of the object.
     * @type {string}
     * @memberof Transaction
     */
    createdAt?: string;
    /**
     * The last update date of the object.
     * @type {string}
     * @memberof Transaction
     */
    updatedAt?: string;
    /**
     * The current version of the object.
     * @type {number}
     * @memberof Transaction
     */
    version?: number;
}

/**
 * Check if a given object implements the Transaction interface.
 */
export function instanceOfTransaction(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "from" in value;
    isInstance = isInstance && "createdBy" in value;
    isInstance = isInstance && "subTransactions" in value;
    isInstance = isInstance && "pointOfSale" in value;

    return isInstance;
}

export function TransactionFromJSON(json: any): Transaction {
    return TransactionFromJSONTyped(json, false);
}

export function TransactionFromJSONTyped(json: any, ignoreDiscriminator: boolean): Transaction {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'from': UserFromJSON(json['from']),
        'createdBy': UserFromJSON(json['createdBy']),
        'subTransactions': ((json['subTransactions'] as Array<any>).map(SubTransactionFromJSON)),
        'pointOfSale': PointOfSaleRevisionFromJSON(json['pointOfSale']),
        'createdAt': !exists(json, 'createdAt') ? undefined : json['createdAt'],
        'updatedAt': !exists(json, 'updatedAt') ? undefined : json['updatedAt'],
        'version': !exists(json, 'version') ? undefined : json['version'],
    };
}

export function TransactionToJSON(value?: Transaction | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'from': UserToJSON(value.from),
        'createdBy': UserToJSON(value.createdBy),
        'subTransactions': ((value.subTransactions as Array<any>).map(SubTransactionToJSON)),
        'pointOfSale': PointOfSaleRevisionToJSON(value.pointOfSale),
        'createdAt': value.createdAt,
        'updatedAt': value.updatedAt,
        'version': value.version,
    };
}

