/* tslint:disable */
/* eslint-disable */
/**
 * sudosos-back-end
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { BaseVatGroupResponse } from './BaseVatGroupResponse';
import {
    BaseVatGroupResponseFromJSON,
    BaseVatGroupResponseFromJSONTyped,
    BaseVatGroupResponseToJSON,
} from './BaseVatGroupResponse';
import type { DineroObjectResponse } from './DineroObjectResponse';
import {
    DineroObjectResponseFromJSON,
    DineroObjectResponseFromJSONTyped,
    DineroObjectResponseToJSON,
} from './DineroObjectResponse';

/**
 * 
 * @export
 * @interface TransactionReportVatEntryResponse
 */
export interface TransactionReportVatEntryResponse {
    /**
     * 
     * @type {BaseVatGroupResponse}
     * @memberof TransactionReportVatEntryResponse
     */
    vat: BaseVatGroupResponse;
    /**
     * 
     * @type {DineroObjectResponse}
     * @memberof TransactionReportVatEntryResponse
     */
    totalInclVat: DineroObjectResponse;
    /**
     * 
     * @type {DineroObjectResponse}
     * @memberof TransactionReportVatEntryResponse
     */
    totalExclVat: DineroObjectResponse;
}

/**
 * Check if a given object implements the TransactionReportVatEntryResponse interface.
 */
export function instanceOfTransactionReportVatEntryResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "vat" in value;
    isInstance = isInstance && "totalInclVat" in value;
    isInstance = isInstance && "totalExclVat" in value;

    return isInstance;
}

export function TransactionReportVatEntryResponseFromJSON(json: any): TransactionReportVatEntryResponse {
    return TransactionReportVatEntryResponseFromJSONTyped(json, false);
}

export function TransactionReportVatEntryResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransactionReportVatEntryResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'vat': BaseVatGroupResponseFromJSON(json['vat']),
        'totalInclVat': DineroObjectResponseFromJSON(json['totalInclVat']),
        'totalExclVat': DineroObjectResponseFromJSON(json['totalExclVat']),
    };
}

export function TransactionReportVatEntryResponseToJSON(value?: TransactionReportVatEntryResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'vat': BaseVatGroupResponseToJSON(value.vat),
        'totalInclVat': DineroObjectResponseToJSON(value.totalInclVat),
        'totalExclVat': DineroObjectResponseToJSON(value.totalExclVat),
    };
}

