/* tslint:disable */
/* eslint-disable */
/**
 * sudosos-back-end
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { BaseProductResponse } from './BaseProductResponse';
import {
    BaseProductResponseFromJSON,
    BaseProductResponseFromJSONTyped,
    BaseProductResponseToJSON,
} from './BaseProductResponse';
import type { DineroObjectResponse } from './DineroObjectResponse';
import {
    DineroObjectResponseFromJSON,
    DineroObjectResponseFromJSONTyped,
    DineroObjectResponseToJSON,
} from './DineroObjectResponse';

/**
 * 
 * @export
 * @interface TransactionReportEntryResponse
 */
export interface TransactionReportEntryResponse {
    /**
     * The amount of times this product is in the report
     * @type {number}
     * @memberof TransactionReportEntryResponse
     */
    count: number;
    /**
     * 
     * @type {BaseProductResponse}
     * @memberof TransactionReportEntryResponse
     */
    product: BaseProductResponse;
    /**
     * 
     * @type {DineroObjectResponse}
     * @memberof TransactionReportEntryResponse
     */
    totalInclVat: DineroObjectResponse;
    /**
     * 
     * @type {DineroObjectResponse}
     * @memberof TransactionReportEntryResponse
     */
    totalExclVat: DineroObjectResponse;
}

/**
 * Check if a given object implements the TransactionReportEntryResponse interface.
 */
export function instanceOfTransactionReportEntryResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "count" in value;
    isInstance = isInstance && "product" in value;
    isInstance = isInstance && "totalInclVat" in value;
    isInstance = isInstance && "totalExclVat" in value;

    return isInstance;
}

export function TransactionReportEntryResponseFromJSON(json: any): TransactionReportEntryResponse {
    return TransactionReportEntryResponseFromJSONTyped(json, false);
}

export function TransactionReportEntryResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransactionReportEntryResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'count': json['count'],
        'product': BaseProductResponseFromJSON(json['product']),
        'totalInclVat': DineroObjectResponseFromJSON(json['totalInclVat']),
        'totalExclVat': DineroObjectResponseFromJSON(json['totalExclVat']),
    };
}

export function TransactionReportEntryResponseToJSON(value?: TransactionReportEntryResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'count': value.count,
        'product': BaseProductResponseToJSON(value.product),
        'totalInclVat': DineroObjectResponseToJSON(value.totalInclVat),
        'totalExclVat': DineroObjectResponseToJSON(value.totalExclVat),
    };
}

