/* tslint:disable */
/* eslint-disable */
/**
 * sudosos-back-end
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdatePointOfSaleRequest
 */
export interface UpdatePointOfSaleRequest {
    /**
     * Name of the POS
     * @type {string}
     * @memberof UpdatePointOfSaleRequest
     */
    name: string;
    /**
     * Whether this POS requires users to
     * authenticate themselves before making a transaction
     * @type {boolean}
     * @memberof UpdatePointOfSaleRequest
     */
    useAuthentication: boolean;
    /**
     * 
     * @type {Array<number>}
     * @memberof UpdatePointOfSaleRequest
     */
    containers?: Array<number>;
    /**
     * ID of the POS to update.
     * @type {number}
     * @memberof UpdatePointOfSaleRequest
     */
    id: number;
}

/**
 * Check if a given object implements the UpdatePointOfSaleRequest interface.
 */
export function instanceOfUpdatePointOfSaleRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "useAuthentication" in value;
    isInstance = isInstance && "id" in value;

    return isInstance;
}

export function UpdatePointOfSaleRequestFromJSON(json: any): UpdatePointOfSaleRequest {
    return UpdatePointOfSaleRequestFromJSONTyped(json, false);
}

export function UpdatePointOfSaleRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdatePointOfSaleRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'useAuthentication': json['useAuthentication'],
        'containers': !exists(json, 'containers') ? undefined : json['containers'],
        'id': json['id'],
    };
}

export function UpdatePointOfSaleRequestToJSON(value?: UpdatePointOfSaleRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'useAuthentication': value.useAuthentication,
        'containers': value.containers,
        'id': value.id,
    };
}

