/* tslint:disable */
/* eslint-disable */
/**
 * sudosos-back-end
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Container } from './Container';
import {
    ContainerFromJSON,
    ContainerFromJSONTyped,
    ContainerToJSON,
} from './Container';
import type { Product } from './Product';
import {
    ProductFromJSON,
    ProductFromJSONTyped,
    ProductToJSON,
} from './Product';

/**
 * 
 * @export
 * @interface UpdatedContainer
 */
export interface UpdatedContainer {
    /**
     * 
     * @type {Container}
     * @memberof UpdatedContainer
     */
    container: Container;
    /**
     * 
     * @type {Array<Product>}
     * @memberof UpdatedContainer
     */
    products: Array<Product>;
    /**
     * The creation date of the object.
     * @type {string}
     * @memberof UpdatedContainer
     */
    createdAt?: string;
    /**
     * The last update date of the object.
     * @type {string}
     * @memberof UpdatedContainer
     */
    updatedAt?: string;
    /**
     * The current version of the object.
     * @type {number}
     * @memberof UpdatedContainer
     */
    version?: number;
}

/**
 * Check if a given object implements the UpdatedContainer interface.
 */
export function instanceOfUpdatedContainer(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "container" in value;
    isInstance = isInstance && "products" in value;

    return isInstance;
}

export function UpdatedContainerFromJSON(json: any): UpdatedContainer {
    return UpdatedContainerFromJSONTyped(json, false);
}

export function UpdatedContainerFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdatedContainer {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'container': ContainerFromJSON(json['container']),
        'products': ((json['products'] as Array<any>).map(ProductFromJSON)),
        'createdAt': !exists(json, 'createdAt') ? undefined : json['createdAt'],
        'updatedAt': !exists(json, 'updatedAt') ? undefined : json['updatedAt'],
        'version': !exists(json, 'version') ? undefined : json['version'],
    };
}

export function UpdatedContainerToJSON(value?: UpdatedContainer | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'container': ContainerToJSON(value.container),
        'products': ((value.products as Array<any>).map(ProductToJSON)),
        'createdAt': value.createdAt,
        'updatedAt': value.updatedAt,
        'version': value.version,
    };
}

