/* tslint:disable */
/* eslint-disable */
/**
 * sudosos-back-end
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { BorrelkaartGroup } from './BorrelkaartGroup';
import {
    BorrelkaartGroupFromJSON,
    BorrelkaartGroupFromJSONTyped,
    BorrelkaartGroupToJSON,
} from './BorrelkaartGroup';
import type { User } from './User';
import {
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
} from './User';

/**
 * 
 * @export
 * @interface UserBorrelkaartGroup
 */
export interface UserBorrelkaartGroup {
    /**
     * 
     * @type {User}
     * @memberof UserBorrelkaartGroup
     */
    user: User;
    /**
     * 
     * @type {BorrelkaartGroup}
     * @memberof UserBorrelkaartGroup
     */
    borrelkaartGroup: BorrelkaartGroup;
    /**
     * The creation date of the object.
     * @type {string}
     * @memberof UserBorrelkaartGroup
     */
    createdAt?: string;
    /**
     * The last update date of the object.
     * @type {string}
     * @memberof UserBorrelkaartGroup
     */
    updatedAt?: string;
    /**
     * The current version of the object.
     * @type {number}
     * @memberof UserBorrelkaartGroup
     */
    version?: number;
}

/**
 * Check if a given object implements the UserBorrelkaartGroup interface.
 */
export function instanceOfUserBorrelkaartGroup(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "user" in value;
    isInstance = isInstance && "borrelkaartGroup" in value;

    return isInstance;
}

export function UserBorrelkaartGroupFromJSON(json: any): UserBorrelkaartGroup {
    return UserBorrelkaartGroupFromJSONTyped(json, false);
}

export function UserBorrelkaartGroupFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserBorrelkaartGroup {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'user': UserFromJSON(json['user']),
        'borrelkaartGroup': BorrelkaartGroupFromJSON(json['borrelkaartGroup']),
        'createdAt': !exists(json, 'createdAt') ? undefined : json['createdAt'],
        'updatedAt': !exists(json, 'updatedAt') ? undefined : json['updatedAt'],
        'version': !exists(json, 'version') ? undefined : json['version'],
    };
}

export function UserBorrelkaartGroupToJSON(value?: UserBorrelkaartGroup | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'user': UserToJSON(value.user),
        'borrelkaartGroup': BorrelkaartGroupToJSON(value.borrelkaartGroup),
        'createdAt': value.createdAt,
        'updatedAt': value.updatedAt,
        'version': value.version,
    };
}

