/* tslint:disable */
/* eslint-disable */
/**
 * sudosos-back-end
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { DineroObject } from './DineroObject';
import {
    DineroObjectFromJSON,
    DineroObjectFromJSONTyped,
    DineroObjectToJSON,
} from './DineroObject';

/**
 * 
 * @export
 * @interface VatDeclarationRow
 */
export interface VatDeclarationRow {
    /**
     * ID of the VAT group
     * @type {number}
     * @memberof VatDeclarationRow
     */
    id?: number;
    /**
     * Name of the VAT group
     * @type {string}
     * @memberof VatDeclarationRow
     */
    name?: string;
    /**
     * Percentage of VAT in this group
     * @type {number}
     * @memberof VatDeclarationRow
     */
    percentage?: number;
    /**
     * 
     * @type {Array<DineroObject>}
     * @memberof VatDeclarationRow
     */
    values?: Array<DineroObject>;
}

/**
 * Check if a given object implements the VatDeclarationRow interface.
 */
export function instanceOfVatDeclarationRow(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function VatDeclarationRowFromJSON(json: any): VatDeclarationRow {
    return VatDeclarationRowFromJSONTyped(json, false);
}

export function VatDeclarationRowFromJSONTyped(json: any, ignoreDiscriminator: boolean): VatDeclarationRow {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'percentage': !exists(json, 'percentage') ? undefined : json['percentage'],
        'values': !exists(json, 'values') ? undefined : ((json['values'] as Array<any>).map(DineroObjectFromJSON)),
    };
}

export function VatDeclarationRowToJSON(value?: VatDeclarationRow | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'percentage': value.percentage,
        'values': value.values === undefined ? undefined : ((value.values as Array<any>).map(DineroObjectToJSON)),
    };
}

