/* tslint:disable */
/* eslint-disable */
/**
 * sudosos-back-end
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VatGroup
 */
export interface VatGroup {
    /**
     * Name of the VAT group
     * @type {string}
     * @memberof VatGroup
     */
    name?: string;
    /**
     * VAT percentage
     * @type {number}
     * @memberof VatGroup
     */
    percentage?: number;
    /**
     * Whether this group is soft-deleted
     * @type {boolean}
     * @memberof VatGroup
     */
    deleted?: boolean;
    /**
     * Whether this group is hidden from transactions
     * @type {boolean}
     * @memberof VatGroup
     */
    hidden?: boolean;
    /**
     * The creation date of the object.
     * @type {string}
     * @memberof VatGroup
     */
    createdAt?: string;
    /**
     * The last update date of the object.
     * @type {string}
     * @memberof VatGroup
     */
    updatedAt?: string;
    /**
     * The current version of the object.
     * @type {number}
     * @memberof VatGroup
     */
    version?: number;
}

/**
 * Check if a given object implements the VatGroup interface.
 */
export function instanceOfVatGroup(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function VatGroupFromJSON(json: any): VatGroup {
    return VatGroupFromJSONTyped(json, false);
}

export function VatGroupFromJSONTyped(json: any, ignoreDiscriminator: boolean): VatGroup {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'percentage': !exists(json, 'percentage') ? undefined : json['percentage'],
        'deleted': !exists(json, 'deleted') ? undefined : json['deleted'],
        'hidden': !exists(json, 'hidden') ? undefined : json['hidden'],
        'createdAt': !exists(json, 'createdAt') ? undefined : json['createdAt'],
        'updatedAt': !exists(json, 'updatedAt') ? undefined : json['updatedAt'],
        'version': !exists(json, 'version') ? undefined : json['version'],
    };
}

export function VatGroupToJSON(value?: VatGroup | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'percentage': value.percentage,
        'deleted': value.deleted,
        'hidden': value.hidden,
        'createdAt': value.createdAt,
        'updatedAt': value.updatedAt,
        'version': value.version,
    };
}

